### ISSUE TITLE
Animetoon

### ISSUE THREAD

**Issue by bjgood** [jewbmx/repo#10]
Hey jewbmx,
Not sure on your end, but on mine, animetoon is down. It was working a couple of days ago. Toonget is working, though.

Have a good one.

**Comment by bjgood** [comment]
Nevermind. I named the wrong source. It's cartoonwire that is not working.

Sorry about that.

Later...

**Comment by jewbmx** [comment]
Thanks for pointing it out, its page is blank so idk whats up lol but o well the site didnt offer much so its no huge loss. Ill remove it on my next update.

**Comment by bjgood** [comment]
Yeah, the site is blank. Maybe it's temporary.

Kimcartoon.tv is a good site.

**Comment by jewbmx** [comment]
Ill add it to my list but no promises lol, tried making toon scrapers a few times and they are some complicated tricky lil bastards todo lmao. Also havent seen anyone else make any either besides the old ones that are dying off

**Comment by bjgood** [comment]
No promises necessary, dude. And, no biggie anyways. Watchnixtoons is still going strong (the kids love this one).

Just know we really appreciate all the work you put into your creations. :).

Later...
