### ISSUE TITLE
Scrubs v2: Trakt > TV > Progress doesn't work.

### ISSUE THREAD

**Issue by SubEdict** [jewbmx/repo#10]
Hi J
Just got the latest Scrubs v2 update and everything works **except** Trakt TV **Progress**, other Trakt List / Watchlists / History etc works fine.
All I'm getting is the spinning wheel for about 30 seconds and nothing happens (back to menu), retried 5, 6..10 times but can't get it to fetch my progress episodes.
*Also installed The Promise and Progress works fine there (just 5-6 episodes).

Tested  on 3 PC Win 7/10 x64. Kodi 19.4.
Any Idea why this is happening on most of the addons (eg. Crew, Marvin) but do work on some?

**Comment by jewbmx** [comment]
My list is quite huge so it always loads slow for me but it still loads eventually lol, besides it going slow its loading on my firestick, phone, and laptop.  Might be extra slow compared to other addons because i dont use the cache function like most people do but i dont really see any errors or issues besides it only loading 50ish of my shows instead of the 100+ i have active lol

**Comment by SubEdict** [comment]
Mine is 75k watched episodes / 2200 Shows. Is that considered huge?
So... You're saying that Progress should work but "load slow"(?) Mine just stop no matter how many times I tried.
Thanks for the replay.

**Comment by jewbmx** [comment]
Id suggest clearing all cache then trying again without interrupting the loading process then if that dont work probably need to check everything out like settings and script.trakt and whatnot.  Your the only one that seems to have the issue as far as i know.

**Comment by jewbmx** [comment]
Im about to upload a new update which should be synced for installation in kodi about 20ish minutes from now lol. But let me know if your progress list issues are solved now or still fuckered up.

**Comment by SubEdict** [comment]
After the update: Sorry, everything in Trakt works except Progress ..yeah bummer, very strange.

Btw, Posting the issue here was actually my last attempt after doing everything else inc': clearing all cache, re-authorize, re-install, revoke connected apps (site). Was using Scrubs maybe since Kodi 17 and Progress always works until this 19.xx version.

Did checked again TV-Progress on all my addons: 
**Works ok**: Asgard, Marvin, Promise, Elementum (my default 99% of use --Works great with Progress-Wiget on the home screen, Aeon Nox Silvo skin).
**Doesn't work:** The Crew, Nightwings, Scrubs v2.

Will keep trying, appreciate all your effort

**Comment by jewbmx** [comment]
Only things i can think of that could cause issues like that is kodi version not being 19+, installed ontop of the old scrubs version(my older addon before i quit coding publicly.),  or script.trakt.
My only advice left off the top of my head is to try a kcleaner cleanse using its clean and compact option,  or opening scrubs to tools then optional installs and double checking that script.trakt is installed and authed. (Optional Installs is coded to be shortcuts for installing or opening settings if installed.)
Besides that im kinda drawing a blank. All the info we have here tells me it should work but for some dumb reason it isnt lol

**Comment by SubEdict** [comment]
My 19.4 was a clean install, started from scratch. I don't use Trakt addon(Kodi Repo). It's probably some Trakt API weakness/issue, saw some Twitter about updating to stronger servers and people complain about " ErrorAPI sync, Connection timeout 502, 404" it's nothing biggy lol, just strange, maybe in a few days it will suddenly fetch again, same thing happened with Malvin (after3-4 months, last update brought back TV-Progress) . 

Scrubs is still amazing (found 2-3 shows that didn't exist in the p2p multiverse). :)

**Comment by jewbmx** [comment]
Well since i cant seem to help ya with trakt, if ya wanna little tip on sources you can google a show or movie on a pc system and then use your browsers built in tools to jack the iframe source then just copy it and toss it into the resolveurl testing addon 😉 its handy and surprisingly not many people think to do it lol

**Comment by SubEdict** [comment]
> use your browsers built in tools to jack the iframe source then just copy it and toss it into the resolveurl testing addon

Wow, every day you learn something new, that one hell of a tip. 🥇 
Thanks a lot!

**Comment by jewbmx** [comment]
Sounds a bit strenuous but its actually pretty handy and i end up doing it quite often when im on a binge and dont wanna stop to make a new scraper to watch my shit lol. And fuck the real sites and their garbage players and ads

**Comment by SubEdict** [comment]
Finally! Good news, last version works. Even found 2 shows that never had sources, now that's a Progress!
Million thanks @jewbmx 👍
