### ISSUE TITLE
Scrubsv2 artwork

### ISSUE THREAD

**Issue by bjgood** [jewbmx/repo#11]
Hey Jewbmx,
First of all, thanks for the update. Mucho appreciated.

Have you been able to find the reason why artwork doesn't show when you open Scrubsv2 in thumbnail view? The other day, after trying Scrubsv2 for a second time, I jumped in and went over the code looking for any simple errors, but I couldn't find anything that wrong. It should work. Strange.

Which addon was the base for Scrubsv2?

If the artwork works for you then sorry for the post.

Have a good one. :).

**Comment by jewbmx** [comment]
Scrubs was originally the yoda addon but probably has a little of everything now lol.
Didnt know there was a error but ill see if i can figure it out too.

**Comment by jewbmx** [comment]
I only have list, shift, icons, and wall for view choices lol. How do ya get it to thumbnail?

**Comment by bjgood** [comment]
thumbnail view was there when I tried it last. Don't understand why it's not showing. I'll try scrubsv2 again tomorrow. I'll be in touch.

Thanks for your hard work, jewbmx. If it wasn't for you, Tempest, and doko, I don't know what this community would do. I wish more coders had your good hearts. ResolveUrl needs help bad.

Best regards.

**Comment by jewbmx** [comment]
I think your issue might just be a skin thing, im on aeon nox silvo and im guessing your on a different skin lol because some views seem to vary.

**Comment by jewbmx** [comment]
Guess i should add that i dont know nothing about resolveurl so i couldnt offer help to it if i wanted, sad days for tvbox.py, Also your welcome lol.

**Comment by bjgood** [comment]
Call me old-fashion but I use the Confluence skin in Kodi 18 Leia (LibreElec) on a RPi 3. It might be a skin thing.

Later...

**Comment by bjgood** [comment]
Hey Jewbmx,
I installed Scrubsv2 today, and the same thing happened as last time. I even tried the Estuary skin...same thing.

Think I'll give up while I'm behind. ;).

I will say Scrubsv2 functioned quite nicely. It was quick, clean, and everything worked. You took your own path on this one. Congrats.

Later...

**Comment by jewbmx** [comment]
If you wanna share some screenshots of your problem i can try figuring out how to make it work for ya. I dont ever use any other skins besides silvo so im not sure whats up with it lol.
