### ISSUE TITLE
Hanging 100% 

### ISSUE THREAD

**Issue by ringobrodgar** [jewbmx/repo#11]
does connect to sources but  after a few seconds of play displays 100% and crashes I have deleted the kodi folder in appdata 
some videos play still getting the issue on others

**Comment by jewbmx** [comment]
If this is a real issue and not just a one host used problem imma need some more info/context lol

**Comment by ringobrodgar** [comment]
I do 2nd line IT support if you can be more specific about what your requirements are I will investigate more thoroughly
My hunch is that the files uploaded to the host are corrupt and it isnt actually an issue with your program
