### ISSUE TITLE
0123putlocker.py

### ISSUE THREAD

**Issue by bjgood** [jewbmx/repo#12]
Hey Jewbmx,
If you get a chance check out 0123putlocker.py. On my end, I'm getting a Google captcha when I go to the site (http://0123putlocker.com). Might just be temporary.

Have a good one up there in Iowa.

**Comment by jewbmx** [comment]
Lol you can mention things like this in the normal chat post if ya want. 

There are spares for that in putlockersplus like  putlockertv.ws  just swap it out for now and ill update the scraper on my end soon.

**Comment by bjgood** [comment]
Yeah, I noticed that those putlocker sources are pretty much the same.

I'll close this thread now.
