### ISSUE TITLE
Update 5.0.17 has slowed down finding TV episode sources on Trakt Collection.

### ISSUE THREAD

**Issue by justmygithub123** [jewbmx/repo#13]
Thank you for your hard work with Scrubs v2. The last update 5.0.17 seems to have slowed down searches for TV shows on my Trakt Collection list. When you click on a TV episode you have to wait about 30 seconds for **anything** to happen "no pop up" for 30 seconds, then when the pop up starts and all sources are found, again there is a pause of several seconds for the results to show. This was not normal behaviour, before the last update. I have cleared all cache/provider's and cleaned settings file. I'm using a Windows PC and it affects Kodi 18.9 and 19.4 portable.

Keep up the great work.

**Comment by jewbmx** [comment]
Yea i think that is from a cookie code ive used in more scrapers. The initial cookie prep is done on em at the start but i think imma try it a different way to try and fix the slow load problem.
Not sure if i can improve the lag at the end tho i havent thought about it yet lol

**Comment by jewbmx** [comment]
i just uploaded a update, when ya get it (visible in a few minutes) let me know if the changes fix some problems and which ones you still notice.

**Comment by justmygithub123** [comment]
Sorry about my slow reply, I just read your last post, and the good news is it fixed everything on Kodi 18.9 and 19.4
Thanks for the fast fix.

BTW, don't get too involved with live feeds there a nightmare to keep up-to-date so if you ever feel it's getting to much work drop the live stuff and keep the free hoisters going. Look at "The Crew" addon, I hope they do have a crew working on it.

Thanks again for the fast fix.

**Comment by jewbmx** [comment]
I dont know the addon but i probably have more iptv stuff in my projects folder lol, i have two huge folders from different sources that are like basic m3u files loaded that im converting to json by hand then 2 or 3 url lists of sites i play with that all end up having iptv sites in their own category that i slowly pick at lol.(where the currently available sections in scrubs came from.)
Think i also still have all the old stuff i used to use in the previous scrubs versions from back in the day.

As for the update and whatnot, your welcome but it just gave me a excuse to push a update sooner to fix my own lil issues that were bugging me lol. If only i would of started watching this show house before i did it so i could of included the fix i did for the custom search title 😀
