### ISSUE TITLE
Nothing in the TV shows section

### ISSUE THREAD

**Issue by andyeld** [jewbmx/repo#15]
I updated scrubs be to 5.0.20 and when I opened it there is nothing in the TV show section. Did a reboot of the box but still nothing is showing up there. The movies section is fine though.

**Comment by jewbmx** [comment]
Gonna need alot more info to help you with your problem lol especially since your likely the only one having a issue

**Comment by jewbmx** [comment]
Off the top of my head with the info you tossed, id say goto tools or "right click" and use the cleaning tools widget to clear all cache in the addon then try again. Or if that dont work wipe the addon from your device and install it fresh to see if that helps lol
