### ISSUE TITLE
At tv-shows the Genre section is not working

### ISSUE THREAD

**Issue by chrisnikol** [jewbmx/repo#17]
Thank you for this amazing addon.

At Scrubs v2 the Genre section is not working.
I am running Kodi 18.1 64bit my OS is Win10 pro 64bit
The version of the addon i am running is 4.3.2
I tried to clear the cache but this dident make any difference.

I upload a video where you can see the behavor of the addon.

Thank you once more for your work!!!!!!

https://youtu.be/dJoPFdJ2oh8

**Comment by jewbmx** [comment]
Recheck the options you had issues with after updateing the module to 4.3.0

**Comment by chrisnikol** [comment]
Thanks, now seems everything working fine.

**Comment by jewbmx** [comment]
Sorry for the errors that was my bad from random accidental edits lol. Also thanks for the compliment and for testing to see if the errors are gone now.

**Comment by chrisnikol** [comment]
You are welcome. The compliment is the least i have obligation to  offer to you, since i am enjoying for free your hard work.

And i have to admit that your response time to fix the error it was just amazing !!!
