### ISSUE TITLE
ScraperChat April/2019 (aka ExoChat lol)

### ISSUE THREAD

**Issue by jewbmx** [jewbmx/repo#18]
To start off this months chat imma point out that i just took a old Scrubs module and swapped some bits into my newest update to remove all the errors people seem to be having lately, SO everyone that uses Scrubs should double check any issues they have had in the past 30 days and see if they are still issues or fixed.

Apparently i been making random changes while bullshiting with someone and forgetting to not save lol.

**Comment by jewbmx** [comment]
Heres a url list to play with too since i seem to share one with every new chat lol.

`
###-Resolver shit
https://vidfast.co/
http://oladblock.services/
oladblock.xyz


###-Scraper Shit
https://solidtorrents.net/
https://torrentz2.eu/
https://1337x.to/
https://1337x.is/
https://rarbg.to/torrents.php
https://www.skytorrents.lol/
https://torrents-csv.ml/#/
https://torrentgalaxy.org/
https://worldwidetorrents.to/home.php
https://filelisting.com/result?q=aquaman
https://psarips.net/
https://snahp.it/
https://hdencode.com/
https://www.mkvcage.ws/
http://oneddl.org/

https://streams.now.sh/

https://www5.123movies.fun/

https://europixhd.net/

https://flixtor.to/

https://cine.to/#tt1477834

https://onmovies.se/search/aquaman
https://onmovies.se/film/gvo/Aquaman?ep=24380

# https://watchseriestv.tv/  # from cmovies.cc
https://watchseriestv.tv/search?q=shooter
https://watchseriestv.tv/serial/191-Shooter
https://watchseriestv.tv/episode/171940-Shooter

http://losmovies.sh/free-movie/tt131874/watch-online-the-highwaymen

http://www.snagfilms.com/films/title/the_slaughter_rule  # sucks but worth lookin at.
http://www.snagfilms.com/films/title/the_weather_underground

https://onionplay.net/search/aquaman  # tricky bitch
https://onionplay.net/movies/watch-aquaman-2018-online/

https://www2.bmoviesfree.net/search-query/aquaman+2018/
https://www2.bmoviesfree.net/movie/aquaman-2018/

https://flixgo.co/
https://flixgo.co/movie/1164-aquaman.html

http://xpau.se/  # dbird/torr
http://xpau.se/watch/the-highwaymen

https://ymovies.tv/home/ # has torr now
https://ymovies.tv/film/the-highwaymen-79319/
https://ymovies.tv/film/the-highwaymen-79319/watching/?playermode=#box

http://1movies.pl/movies/search?s=aquaman+2018
http://1movies.pl/film/aquaman-2018-1080p.90150/



http://watch-series.live/ http://watch-series.co and .ru clone.

http://1stream-tv.me/

https://www1.putlockers.net/tvseries  # cfscrape
https://www1.putlockers.net/search?s=shooter

https://5movies.to/tv/hanna-15077-s1e1/


https://animedao.com/
https://www.cartoonson.tv/
http://watchcartoonsonline.eu/
https://m.watchcartoononline.io/
http://www.supercartoons.net/
https://kimcartoon.to/
https://www2.gogoanime.io/
https://www.newgrounds.com/
https://www.cartoonito.co.uk/
http://www.kisspanda.net/
https://www2.9anime.to/
https://www16.kickassanime.io/
https://animeheaven.gg/
https://animeheaven.es/
https://hi10anime.com/
https://animepahe.com/




`

**Comment by doko-desuka** [comment]
Thanks for the new links list.  

After sweating a lot with the docs and doing several passes, I managed to get a simplified DialogSelect (xbmcgui.Dialog().select()) using an XML file.

![customDialogSelect](https://user-images.githubusercontent.com/31810999/55323618-16ac3b80-546f-11e9-9594-e4e27a5467af.png)

The gist:
https://gist.github.com/doko-desuka/de9aa7de9c1a09e1f83e8e2fa036489c

**Comment by jewbmx** [comment]
Np, didnt do much with the list but dont think this one has any gay fakes in it lol.

I'll check out that xml dialog in a bit.

Also uploaded a quick zipfile of that cleaner addon for a buddy to grab. You can too if you are still curious about that list idea i was messing with. (The lists would be in index and then the idea is just adding the custom menu color to those lists and making it all work lol. I get the color in but then break the option like a noob.)

**Comment by bjgood** [comment]
Jewbmx,
I noticed that your cfscrape has sections in it such as operators, eval_expr(expr), and eval_(node). Briefly, what are they suppose to accomplish? Is yours better than the one I linked to from openscrapers?

Thank you.

**Comment by jewbmx** [comment]
Idk lol google i guess

**Comment by bjgood** [comment]
Does IDK mean "I don't know"? I'm not hip on all this city folk lingo. :).

**Comment by jewbmx** [comment]
Yup and thats a google moment too lmao

**Comment by jewbmx** [comment]
Im curious on if doko is gonna hook us up with a gist to his cfscrape version lol, probably the only version i havent tested yet

**Comment by bjgood** [comment]
Just copy everything below "def cfSolveChallenge" in his code. Then paste over everything from "solve_cf_challenge", down to and including "parseJSString" into your cfscrape.py. That's what I did. I'm sure you know that to do. If a nitwit like me can do it, poorly I'm sure, anyone can.

They all (yours, openscrapers, and his version) work. Trying to decide which one to use. They all produce the same amount of results, at least on the series I've tried.

Later...

**Comment by jewbmx** [comment]
Yea your no help lmao. On a plus side, i just got my s list idea to work properly with color so i can finish this cleaner with no excuses now besides having to double check all the imports again.

**Comment by bjgood** [comment]
It didn't work for you?

**Comment by bjgood** [comment]
Doko. I know you're here. Post something for your old friend Jewbmx. He needs help. ;).

**Comment by jewbmx** [comment]
Theres a folder in my en folder called fuckit you can test it against lol, if it doesnt get atleast 5 of the scrapers to work then it isnt worth it for me to switch. Think ive only pulled out about 2 or 3 of em since my last update

**Comment by doko-desuka** [comment]
What @bjgood said is right, cfSolveChallenge = solve_cf_challenge function in that class, and then all the other functions take the place of parseJSString.

(If you keep the name as cfSolveChallenge then you also need to rename the call inside the request() function, as it calls to the old name "solve_cf_challenge")

**Comment by bjgood** [comment]
Timewatch and seriesfree are working. Of course, they were working before I tested some from the folder you mentioned. I don't use debrid sources. The rest that I tried...123movieshubz, filep, hdtoday, mymoviesonline, pubfilmonline, sharemovies, solarmovie, and sunmovies...were a no go.

I assume the code is good as to why they're not working.

Like I mentioned, they all seem to produce the same output.

I gave it shot.

**Comment by jewbmx** [comment]
No worries lol, i think the ones that work got a cloudflare update and the ones that are broken are probably still rockin a old cloudflare. Either way i dont mind lol the scrapers i use work for me.

**Comment by doko-desuka** [comment]
Hmm, thanks for the warning @bjgood, you're right, there was a mistake in there (wrong index to grab from the string).

**Comment by jewbmx** [comment]
Oh shit started making a scraper for yesmovies.gg and found they came out with another new flick  justice-league-vs-the-fatal-five

**Comment by jewbmx** [comment]
Doko im not seeing any change when i swap to yours. Might be less in the debug log but the results seem the same for scrapers

**Comment by doko-desuka** [comment]
Try changing the \_\_init\_\_ function to this:
```
    def __init__(self, *args, **kwargs):
        super(CloudflareScraper, self).__init__(*args, **kwargs)

        if "requests" in self.headers["User-Agent"]:
            # Spoof browser headers.
            self.headers.update({
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                'User-Agent': DEFAULT_USER_AGENT,
                'Accept-Language': 'en-US,en;q=0.5',
                'Cache-Control': 'no-cache',
                'Pragma': 'no-cache',            
                'DNT': '1'
            })
```

If the add-on you're using doesn't add its own headers to the request it'll be easy for CF to tell that it's coming from a bot and not a genuine web browser.

**Comment by bjgood** [comment]
Same results as Jewbmx even with the above code supplied by doko.

**Comment by jewbmx** [comment]
My debug is filled with all kinds of errors from cfscrape no matter what one is used lol. I just dont give a shit no more. Imma simply comment out the debug lines and leave the junk alone :)

**Comment by doko-desuka** [comment]
Okay, maybe it's better to wait a couple months before trying it again. Their tech is in a period of changes right now, it's easier to debug something that stays still x)

**Comment by Tempest0580** [comment]
Jewbmx use doko-desuka version, im not getting any errors from his, Testing it now, Its looks good so far, Thanks Doko

**Comment by doko-desuka** [comment]
Thanks Tempest, I can predict it failing in 3... 2... 1... xD

**Comment by bjgood** [comment]
Jewbmx and Tempest,
Did the both of you add the above headers code of doko's to his cfscrape file?

**Comment by Tempest0580** [comment]
I added it in and it did a lot of the scrapers work again.

**Comment by bjgood** [comment]
Yeah, you added it in alright. Just had a look at your latest release. You do good work, Tempest. Like Jewbmx, I "borrow" some of your creations, too.

Thanks for the response.

**Comment by jewbmx** [comment]
I got it going after a bit and it fixed a couple of the main ones that were down. My last error issue was some retarded ascii error that took a second to spot lol.

**Comment by jewbmx** [comment]
Might be able to enjoy scraper work again now thanks to doko lol. My log is all pretty again too...

`[2019-04-03 23:05:00] [ [COLOR orange]Scrubs v2[/COLOR]  DEBUG ]: Request-Error (401): http://www.omdbapi.com/?i=tt0089218&plot=short&r=json&apikey=74703860
[2019-04-03 23:05:00] [ [COLOR orange]Scrubs v2[/COLOR]  DEBUG ]: Request-Error (401): http://www.omdbapi.com/?i=tt1846589&plot=short&r=json&apikey=74703860
[2019-04-03 23:05:14] [ [COLOR orange]Scrubs v2[/COLOR]  DEBUG ]: Request-Error: (unknown url type: /watch-hunter-killer-online.html) => /watch-hunter-killer-online.html
[2019-04-03 23:05:14] [ [COLOR orange]Scrubs v2[/COLOR]  DEBUG ]: SolarMovie - Exception: 
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.scrubsv2/lib/resources/lib/sources/en/solarmovie.py", line 41, in sources
    Links = re.compile('id="link_.+?target="_blank" id="(.+?)"',re.DOTALL).findall(html)
TypeError: expected string or buffer
[2019-04-03 23:05:43] [ [COLOR orange]Scrubs v2[/COLOR]  DEBUG ]: Request-Error: (HTTP Error 503: Service Temporarily Unavailable) => https://0dayreleases.com/?s=Hunter+Killer+2018
[2019-04-03 23:05:44] [ [COLOR orange]Scrubs v2[/COLOR]  DEBUG ]: Request-Error: (HTTP Error 503: Service Temporarily Unavailable) => https://0dayreleases.com/?s=Hunter+Killer+2018
`

**Comment by jewbmx** [comment]
If anyone wants to mess with it, i found a decent site earlier that turns out to be a headache of a scraper lol. It will scrape but cant seem to make it play lmao  fastmovies.online

**Comment by doko-desuka** [comment]
Yo jew, that fastmovies site looks really fresh, it didnt put any TV series up yet. What sorcery did you use to find it? I can only find shit

**Comment by jewbmx** [comment]
I tried twice and couldnt make one that played so i threw it away lol. My usual income of domains is just google, duckduck, and main ones my century link search from my net provider lol. Sometimes i find a decent blog list too

**Comment by jewbmx** [comment]
Http `webhelper.centurylink.com` is the url for what i thinks the best way to snag new ones lol

**Comment by doko-desuka** [comment]
Great tips, thanks.

**Comment by jewbmx** [comment]
Dont know exactly what impact it makes or if its the real site but thexem.de is back up.

**Comment by bjgood** [comment]
I'm posting this reluctantly, but it works for me. I found this bit of code over at Anorov,s github.

To try it, first remove doko's test and revert it back to the way it was.

Second, add this bit of code at the def request function...

    def request(self, method, url, *args, **kwargs):
        self.headers['Accept-Encoding'] = 'gzip, deflate'
        self.headers['Accept-Language'] = 'en-US,en;q=0.9'
        self.headers['DNT'] = '1'
        resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)

This bit of code got hdtoday to start working in TV series. In movies, it got moviesoline and sharemovies to start working. Your mileage may vary.

What have you got to lose by trying it?

**Comment by jewbmx** [comment]
5 minites of my life, half a high, 2% of my phone battery. Lmao

On a side note for that thexem shit, it must need some work because it makes problems when you uncomment the line for it.

**Comment by bjgood** [comment]
Did it work for you?

**Comment by jewbmx** [comment]
Oh i didnt try it lol was just talkin a little shit. I ended up jacking the exact same cfscrape file tempest has in right now from doko and ran a test on every scraper i got in lol. Anything that failed got tossed in the temp folder to be forgotten or fixed later lmao

**Comment by bjgood** [comment]
Chicken shit! Try it. Sharemovies and mymoviesonline should work. hdtoday wouldn't show until I added this code.

As you know, cutemovies, hdtoday, and sunmovies are pretty much the same site. Code is much the same.

**Comment by jewbmx** [comment]
I got no need to lol. Every scraper i like is working and the ones that dont i got in a temp folder and to be honest the entire folder can be deleted without a care or tear lol.

**Comment by bjgood** [comment]
Hey, it's your choice. I can understand why. You're just tired of messing with it. That's cool.

Hopefully, doko reads this and gives it a go. It's probably another "you're the only one" situations.

The chicken shit thing was just a joke. Don't take it personal, dude.

Later....

**Comment by doko-desuka** [comment]
I'm thinking it's like, every site admin must set up their own CF blockade. That's why some sites use the old block, while some have updated and use the new block. It's up to the admin to do it.

If your favorite sites use the old block, no changes are needed to cfscrape.

**Comment by bjgood** [comment]
Have you tried it, doko? I'm just saying that new stuff shows up on a scan with that code in it.

**Comment by doko-desuka** [comment]
I haven't tried exactly that code you posted, but I do that in \_\_init\_\_ since it only needs to be done once when the Session object is created. Using headers is good in any case, makes it look like you're some guy in a web browser.  
The "Accept-Encoding" header isn't needed, Python.requests only supports "gzip, deflate" anyway, so it starts with that header already set.

**Comment by jewbmx** [comment]
I looked around a little at thexem.de's doc page to see if the code in our forks is valid and it all looks right to me, not sure if it works lol but i added a try:   except: pass to and let it try to do its thing anyways lol

**Comment by jewbmx** [comment]
Heres a odd one that might be worth checking out lol `https://streamhi.000webhostapp.com/` takes a couple seconds to find your way to the file url and it has a really annoying adblock popup so i decided to close the page lol.

**Comment by jewbmx** [comment]
Anyone recall what it was i did that fixed the tv show person search? It was too far back for my stoner brain and i dont see any history of me pointing out the fix for it lmao.

**Comment by jewbmx** [comment]
I just uploaded a new iptv list meant to be a sports replacement for the broken m3u i had. If anyone wants it i think its a pretty good list, has ufc and wrestling too which i think imma have to get stuck in for a lil bit lol.

**Comment by bjgood** [comment]
Looks like we'll be losing rapidvideo as a host shortly. Take a look at this...

https://torrentfreak.com/freeloading-kodi-add-on-users-are-undermining-rapidvideo-190405/

I'd hate to see it go. Will not leave us many really good ones. Hope others don't follow suit.

**Comment by jewbmx** [comment]
Sorry for deleteing ya bjgood but dont post reddit trash here sir lol. If you wanna share something like that make a gist or remove the link of the url

**Comment by bjgood** [comment]
BTW. Does anyone know where I can find a copy of plugin.video.phoenix from around 2016-2017? It had a section where you could get USTVNow premium (all their premium channels for free).

*Jewbmx. It's not from reddit. It's direct link to torrentfreak. What is so wrong about that link?

**Comment by jewbmx** [comment]
Forgot to mention it in the last update but you guys can use mymoviego.py now without worrying about it being trashy. Gave it a little limit code lol

**Comment by doko-desuka** [comment]
"f2movies dot to" seems to be a clone of "moviesjoy dot net", they have the exact same video links, as well as the name "MoviesJoy" in their FAQ (they forgot to change it lol).  
But it's good to keep in mind in case the other one goes down.

**Comment by jewbmx** [comment]
I just put moviejoy and primewire in my temp folder the other day, someone posted a issue in scraperscraps saying both scrapers cause a glitch in the source search. Havent looked into it yet but it is a valid problem

**Comment by bjgood** [comment]
I don't know what happened yesterday, Jewbmx. What's up, dude? If you've got something to say...say it. I at least deserve an answer.

**Comment by jewbmx** [comment]
Ok figured i said enough to make the point lol.

Lets make it simple, my repo issue page and i dont want drama and gossip.

That shits on reddit already and can be talked about there or in a gist where i wont have to read every comment about it since i could care less to begin with.

**Comment by bjgood** [comment]
I don't visit at reddit very often. I only registered there so I could comment on doko's watchnixtoons2, and your scrubsv2 addon. I was not aware that torrentfreak's article was being discussed at reddit. Assuming I knew about it was a bit unfair. Bringing up that rapidvideo might not be available soon I thought would be of some interest to us. I was just passing it on.

I'm feeling unwelcome here.

Later...

**Comment by doko-desuka** [comment]
hey Jewbmx,
delete this!!

![peen](https://user-images.githubusercontent.com/31810999/55733814-fe5b9400-5a0d-11e9-8827-b22dbf8a2771.png)  
=D

**Comment by bjgood** [comment]
Hey Jewbmx,

Here's a fix for the Cloudflare changes. Find doko's post and apply it to your current cfscrape file (doko's latest file)...

https://github.com/Arias800/CloudflareScraper/issues/3

It works.

Thought you might be interested. :).

**Comment by jewbmx** [comment]
My bad been a little side tracked with some other stuff lol. I actually switched my cfscrape module the other day to one Tempest is using but didnt notice the cf change this time, been on torr only for a couple days testing and changing things lol. Should have a update sometime this morning when im done with what im doin

**Comment by Tempest0580** [comment]
I'm going to double check tonight but I think doko's cfsrape doesn't work with a few of the main debrid scrapers.  Like ddlvalley and bestmoviez.

**Comment by bjgood** [comment]
Hi Jewbmx and Tempest,
Man, Tempest, your cfscrape works really well. It draws in a lot of results. Did you come up with that yourself? It reminds me of doko's latest pull request at Arias800's github but with a lot of changes added.

**Comment by Tempest0580** [comment]
No bjgood I didnt come up with it myself. That's a little above my pay grade. Lol
It was one of the few I tried. Had to tweak it a little bit to make it work though.

**Comment by jewbmx** [comment]
This pos app is glitched again lol.

**Comment by doko-desuka** [comment]
The cfscrape in Tempest's add-on is originally from Yoda, it uses a somewhat different method of solving the problem.  
It's also being used in Addon4Kodi's OpenScrapers, but without the mods that Tempest did.

**Comment by bjgood** [comment]
Tempest did a real good job on that one. Pulls in a lot of results.

Arias800 and doko's latest (released a few hours ago) does a good job, too.

**Comment by jewbmx** [comment]
Imma test it against the scrapers i have left in my temp folder.

Lil tip for anyone using scrubs, disable cinewhale and fmovies to get a faster search time.

**Comment by bjgood** [comment]
Really? I hadn't noticed, but I'll take your advice.

Later, Jewbmx. :).

**Comment by jewbmx** [comment]
Well last time i looked cinewhale was a dead url but it could pop back up if it hasnt already lol, and fmovies is just a slow fucker like most the domains that use that scraper base

**Comment by jewbmx** [comment]
Man everytime i hop on github i see another one of those junk ass scraper modules popup lmao.

Hey Doko do i need to update the cfsolver i use in my resolveurl module?

**Comment by doko-desuka** [comment]
Hi Jew. I'm not sure... The cfscrapes that are going around are based on the 'requests' library, while resolveurl uses its own module for dealing with web requests (they call it the "Net" class).  
Those updates would have to be ported to resolveurl somehow.

But the resolver(s) that would use it are probably obsolete by now, such that it wouldn't make a difference.

**Comment by jewbmx** [comment]
I think the file i was looking at was just one you was using for a patched resolver but i never added any of that to the fork or pr i did so it all ended up getting wiped  anyways lol.

**Comment by jewbmx** [comment]
Damn its been 2 hours since i got side tracked off scraper updates lol poor little guys been on hold

**Comment by doko-desuka** [comment]
> I think the file i was looking at was just one you was using for a patched resolver but i never added any of that to the fork or pr i did so it all ended up getting wiped anyways lol.

It's in a gist, it was for Speedvid I think: https://gist.github.com/doko-desuka/ddf3eb55f557f3c025c610a63c86a920  
The updated method is in here, but as a generic 'requests' based solver: https://github.com/Arias800/CloudflareScraper/blob/master/CloudflareScraper/__init__.py

**Comment by bjgood** [comment]
Doko,
Is your speedvid fix still working for you? I renamed that __init__.py file to cfsolver.py but speedvid still does not work. Can you post a working fix?

**Comment by doko-desuka** [comment]
@bjgood it won't work as a drop-in replacement because of Thais reason:
https://github.com/jewbmx/repo/issues/18#issuecomment-483443840

Resolveurl and Arias800 cfscrape use different tech to communicate with the web.

Someone needs to port the Arias800 cfscrape to resolveurl, like my gist demonstrates (with the old version, anyway).
I think it'd be fair if another dev did this -- maybe someone in the A4K sub?

**Comment by bjgood** [comment]
> Someone needs to port the Arias800 cfscrape to resolveurl, like my gist demonstrates (with the old version, anyway).
> I think it'd be fair if another dev did this -- maybe someone in the A4K sub?

I see.

**Comment by bjgood** [comment]
Nice job on your vidtodo pull request, Jewbmx. It works fine.

Thanks.

**Comment by jewbmx** [comment]
Why you telling me nice job lol that is an old fix from doko that i noticed isnt in the new resolveurl update.

**Comment by bjgood** [comment]
Well. You submitted it. I don't recall doko posting that anywhere. But, if you insist...I withdraw my compliment to you. :).

Later...

**Comment by jewbmx** [comment]
Lol it was posted here months ago if i recall, but you could of read the description on the PR and the update date is in the file :p

**Comment by jewbmx** [comment]
Im about to just modify a scraper like watchepseries to only show one host at a time so i can test resolvers easier. Its kind of a pain in the ass to test em on a normal search

**Comment by bjgood** [comment]
Might want to put mycoolmoviezone and deepmovie back into the lineup. I tried both and they brought up links and played.

**Comment by jewbmx** [comment]
Dope, was hoping deepmovie wouldnt stay down lol. Cant recall why i pulled mycoolmov

**Comment by jewbmx** [comment]
Anybody got any good iptv shit? m3u and what not, been doing a little iptv project with Tempest and imma hunt down some more lists to sort thru today.

**Comment by bjgood** [comment]
Here's one I use...

https://github.com/haroo/HansSettings

They only update the list about once a month. It's about like Fluxus (which you already use).

**Comment by jewbmx** [comment]
Torrents seem to be a little touchy today lol, did 3 tries on one episode and all 3 crashed kodi. Just proof that free is better and that premo services are a joke.

**Comment by jewbmx** [comment]
Hey bjgood you wanna try this out for me? https://github.com/jewbmx/script.module.resolveurl/blob/master/lib/resolveurl/plugins/idtbox.py

Cant tell if my net is running crappy or the sources lol

**Comment by jewbmx** [comment]
I thought there was a resolver for streamcherry dot com but i cant seem to find it also lost my source for it during the hunt so fuck it lol

**Comment by doko-desuka** [comment]
Heya. Streamcherry is part of the Streamango family:
https://github.com/jsergio123/script.module.resolveurl/blob/master/lib/resolveurl/plugins/streamango.py#L35

**Comment by bjgood** [comment]
> Hey bjgood you wanna try this out for me? https://github.com/jewbmx/script.module.resolveurl/blob/master/lib/resolveurl/plugins/idtbox.py
> 
> Cant tell if my net is running crappy or the sources lol

Yeah, it works. Search for "Death in Paradise" season 8 or "Father Brown" season 7. It showed up with source myswatchseri and its variants.

idtbox seems to only have the latest season for a series, at least from my limited observation. But it does show and play. Congrats, Jewbmx.

**Comment by jewbmx** [comment]
Thanks doko that was bugging my brain lol.

And thanks for the test too bjgood, on my end it was playing with a iptv type of quality or a gvideo lol. It will mostly pop up alot for watchep4 watchepser and swatch because i am using watchep4 to do resolver shit lol its got most of em and is pretty easy to snag em off the page lol

**Comment by jewbmx** [comment]
If you guys wanna giggle try to watch the first episode of the new abc show The Fix (2019) tried about 20 of the results and never found the right episode lmao. Enable dbird again and run it on torrent scrapers and the first result you get is a proper match lol.

**Comment by jewbmx** [comment]
Man the stupid cunt uploading all the streamlive bullshit sources with commercials is annoying and retarded but these junk ass sites rocking the same version of it on each host is just as bad

**Comment by bjgood** [comment]
Jewbmx,
Are you getting any working links from vidtodo.py? It appears to be broken again. I tried both movies and tv series.

**Comment by jewbmx** [comment]
Works on my end, just tried one on swatchseri

**Comment by jewbmx** [comment]
Hey doko if you get bored can you double check the idtbox resolver for me? I get the feeling im missing something but cant get it lol

**Comment by bjgood** [comment]
> Works on my end, just tried one on swatchseri

Strange. I'm using the vidtodo.py you posted at JSergio's, but no links work. I've tried a dozen series. It jumps right by any vidtodo links. I've cleaned providers and cache, rebooted, but nothing works.

I'm stumped.

What series did it work for you?

**Comment by jewbmx** [comment]
Idk lol just open your debug log and check your sources by hand to find out if the files even there or hit the site your trying with

**Comment by doko-desuka** [comment]
@jewbmx from looking at it, it seems to do all that's needed to play, but ultimately they'll be able to tell that it's coming from a bot, because of things like cookies set through Javascript, a log request that the player does, among other things. But again, it should play fine.

**Comment by jewbmx** [comment]
Every source i try from that resolver starts like iptv so i dont even plan on using it. But it does seem to be a slightly popular one on a few sites so people might have a use for it.

On my end it always starts green and buffers like ass same as a gvideo source.

**Comment by bjgood** [comment]
Idtbox buffers on my end, too. Right at the beginning of the video.

**Comment by jewbmx** [comment]
That new yesmoviegg has a xstreamcdn version of you know what that is a good copy.

**Comment by jewbmx** [comment]
Anyone wanna test a few scrapers in universal? Heres what seems to be broke on my end

cotun.py / Couchtuner
movienolimit.py / MovieNoLimit
newepisodes.py / New episodes
primewire.py / Primewire
putlockerhd.py / PutlockerHD
seriesonline8.py / Series9
streamdreams.py / StreamDreams
twomovies.py / Twomovies
watchtvseries.py / WatchTVseries

**Comment by bjgood** [comment]
Last time I did a scan (last night) and tried to play anything series9, and streamdreams (Tempest) worked. Along with coolmoviezone, and seriesfree which you put in Temp. Primewire doesn't work at all on my end. This was last night. In this hobby things change, proverbially, "over night".

I'd like to try them if they're non-debrid.

**Comment by jewbmx** [comment]
Lol none of thats helpful, im talking about universal scrapers not exo scrapers

**Comment by bjgood** [comment]
Ohhhh! Sorry, I misunderstood. I try to stay away from universal scrapers at all cost.

You haven't released an update in awhile, Jewbmx. Is universal scrapers your new interest?

Later...

**Comment by jewbmx** [comment]
Lol nope just randomly decided to do some testing on my little nitecrawler addon and noticed barely any scrapers were working

**Comment by jewbmx** [comment]
Hey bj you been around longer then me, does rapidgator require a login to work? Theres always a ton of results for it but they never play lol bout to check the resolver or disable it so they fuck off

**Comment by bjgood** [comment]
I don't know. It appears to be a premium service. It's listed in hostprDict, in sources.py, on my system. I always disable it in resolveurl. I just conducted a test. I signed up for a free account at rapidgator.net, enabled it in resolveurl, entered my username and password, then tried a few scans of tv shows and movies. No links to rapidgator showed. Check out the resolver.

**Comment by jewbmx** [comment]
I just disabled it thru resolveurl for now lol i might mess with it sometime but dont really care for anything that requires an account besides trakt

**Comment by Tempest0580** [comment]
It's a premium service. Debrid doesn't support it however they still play them most of the time.

**Comment by jewbmx** [comment]
Damn you guys are all quick to respond today, must be a dull wednesday lol.

Next dumb question, if i add the trakt options to sky channels do you think it will let ya save the movies to your watchlist? I been lazy and just adding em with a app on my phone but think if it will work i can be even lazier and use the addon lol

**Comment by bjgood** [comment]
Ororo really sucks, too. You have to register. Free account, of course. On a free account you get 30 minutes of view time then they cut you off. I will say that they seem to have everything, though, but I don't want to pay them $10 or $15 dollars per month just to watch Miss Marple, or Poirot (British Mysteries fan here).

**Comment by bjgood** [comment]
Jewbmx,
Is streamango or mycloud working for you? 

BTW, it's May, bud.

Have a good one.

**Comment by jewbmx** [comment]
Not sure just woke up for today but will check. And i know lol i figured id wait to do everything this weekend

**Comment by bjgood** [comment]
Thanks, bud. Neither one has been working for me for the past couple of days. Maybe you can apply that big brain of yours to fixing them if they're down.

**Comment by jewbmx** [comment]
Lol just checked eztvstatus.com to grab their spare domains and the one they show as new doesnt work lmao

**Comment by bjgood** [comment]
Have you tried a streamango or mycloud link? Watch them work for you.

**Comment by jewbmx** [comment]
Lol already commented on your resolveurl post, Mango is working on my end but i havent seen a mycloud yet

**Comment by bjgood** [comment]
Thank, buddy. I saw your post over at JSergio's.

I really appreciate your help on this, Jewbmx. You're a fine fellow. Thumbs up to you.

**Comment by jewbmx** [comment]
10 tries and 4 edits later the scraper gets put in the correct folder

**Comment by jewbmx** [comment]
I still havent seen anything come up for mycloud bjgood, what scraper do you see em on? Also if you check your debug log and look at the url mcloud.to works but mycloud.to looks to be dead

**Comment by bjgood** [comment]
Hey Jewbmx,
I don't recall which scraper it was. And, btw, I did the very same thing you did yesterday. I checked out mycloud (the resolver) and found, like you, that mycloud.to was down, and mcloud.to was up. I even rewrote the resolver to just mcloud.to.

Have a good day, bud. :).
