### ISSUE TITLE
HelpDesk/ChatBox v.2

### ISSUE THREAD

**Issue by jewbmx** [jewbmx/repo#19]
Yimmy Yammerin

**Comment by jewbmx** [comment]
If anyone else has a marvel/dc addiction like me and gets tired of using the usual outlets like my little sections in scrubs lol you can try the more simple route ive been doing lately lol, now that i changed the addons userlist design a bit liked lists are enjoyable so i been rockin em lately and found myself a few good lists to use 😊 
You should be able to click the little thumbs up yourself and like em too if ya wanna lol.
https://trakt.tv/users/jewbmx/lists/liked

**Comment by jewbmx** [comment]
I think i might change my tmdb collections section around a bit extensively lol.
Im thinkin one giant list in my usual ghetto json type of setup and some added details like 'page': page# and genres added from each collection which can be the ways to sort and build a list to see.
The page number seems like a easy way to do the current style of a-c instead of making some odd title scrape and compare nonsense lol.

**Comment by jewbmx** [comment]
My tmdb collections update is pretty much done, i just need to open each page up like the old version to add the a-b  and s-t shit for the label on em lol.

Its now 18 pages for a alphabetical list option instead of the previous like 11. Then a ALL list option thats all 1786 collections saved in the addon code. Plus one more handy option for the genres so you can sort em by picking what genre ya want like Action and it will show you any collections that have Action listed in its genres lol.

**Comment by jewbmx** [comment]
If anyone uses that tmdb helper addon and needs a working player file for scrubs, i just fixed one and uploaded it here in the github.io and temp_space areas. (Only tested with kodi v20, not sure about older kodi v's.)

**Comment by jewbmx** [comment]
Looks like my next project is making the final info defs used for each item be coded in various metadata sources like one for tmdb(default already) then one for trakt and so on.
The goal is to be able to choose which one is used which would fix some issues that come up like the tv show firefly having 14 episodes but tmdb only showing 11 when other sources show the proper 14 lol.
If anyone wants to help out feel free to toss me any code ya might already have, seen, or make lol or toss suggestions even optional sources.

I also recently tossed in a similar setup for searching stuff in Search Tools with some settings as well.(Might add some more sources to this as well like tvmaze and omdb in searching and my previous bit about metadata final_info.)

**Comment by scoob1** [comment]
Hey man just a heads up,the latest update to 5.1.22 seems to have broken the library function
As it stands,scrubs checks for new shows every however often from trakt list and adds new items after they have aired, to the kodi library but since this latest update of scrubs, the message "updating tv shows" flashes for like just 1 or 2 seconds then disappears and nothing happens.
Go back to previous version 5.1.21 and it works again as it should.
Thanks

**Comment by jewbmx** [comment]
Did ya try cleaning things? Or opening the settings and clicking ok so any new ones save incase they didnt automatically already lol.

As far as i know, i didnt really change anything there and what i did change should be optional and only effecting those who set the new settings differently.

**Comment by scoob1** [comment]
Hey yeah ive just updated it back to the latest version and cleared cache and old settings and got the message 0 old setttings deleted.But now when i look in the addon settings it has borked the install including my trakt account not being linked anymore and my linked lists for library have gone and all scrubs settings have gone back to default.:weary:
Im now going to reinstall it completely and scan all the library again from scratch.Fingers crossed it works :sob: :laughing:

**Comment by scoob1** [comment]
So i think i figured out what is causing the problem.Its the new settings that you added "info metadata"
If the tv shows info source is not now set to the same place as our tv show list for library is from,then it is causing the library not to add and update new episodes when they air because it is trying to check/scrape the wrong website.
I never knew that this setting would interfere with the library function.

**Comment by jewbmx** [comment]
Well i looked thru the addon and the only thing i found that could be problematic is the seasons.py i added in to break down the episodes.py better. I just changed that back to how it was, guessing the file name conflicted with the code names in the library code.
So imma upload a new version for ya, you honestly might wanna wipe scrubs out and install it fresh to account for any changes you made or go back thru your settings and set it up the way you had it in the older version. 
As for the new metadata info settings you should leave that as tmdb like i said in my changelog notes.

I await your response on if this update fixes your issues lol 🙂

**Comment by jewbmx** [comment]
I forgot to mention that if ya still have the issue afterwards you might wanna send me your log files to try spotting any errors there, i clear mine in-between each process to spot issues alot that i might not see elsewhere. Like the newer errors that happen from the listitem stuff, that shit errors out often with issues like tuples and whatnot lol.
I personally dont use any library type of features so i cant really reproduce your problem and not real sure how to try setting it up to try either lol. But thanks for being that person to do the testing for me in that section 😀

**Comment by scoob1** [comment]
Hi,i updated to this new version and left the metadata info set to tmdb to test it and the library function is still working now again as it should without having to change the metadata info to trakt,so thanks for the fix.All seems to be back how it was now.:ok_hand:

**Comment by jewbmx** [comment]
30 damn minutes if not more spent fiddling with stupid ass youtube between their garbage api and kodi's wack ass addon, a quick power outage which led to a quick wifi outage, and after like 40+ pairing attempts with their dumb device code input twice at a time, im stuck in the same damn boat where i cant test my trailer code all the way. 😳🙄😒😑

So if anyone finds a problem with my new trailer module yall can go fuck yourself right along with them cunts from google and youtube.

**Comment by E-Thawne** [comment]
Thanks for all your hard work on this addon. but I just want you to know since updating to the new version, you hardly get any links. I reinstalled the previous version & receive more. Think its the movieonline.fm scraper.

**Comment by jewbmx** [comment]
Welp i already figured out my issue i had with the trailer results being duped and needing coded to counter it, i just had to ditch the use of self.list and code the list into each def so the results dont get added in to the total list till the end :)  (doest effect anyone tho so there is no need for another update.)

And @E-Thawne  i didnt do anything that would effect that so your just trippin.

**Comment by jewbmx** [comment]
Ive added in a flixed_io channels section now which is pretty much the same as the tvpassport one, gonna procrastinate on doin another update tho since i been like the google playstore lol

**Comment by jewbmx** [comment]
Heads up to yall, i broke the clean_settings bit of the addon temporarily because the new a4ksubtitles setting i added in needed the & symbol encoded that in its "url" lol.
Its fixed already on my end so it will be working properly without the error on the next update. (Technically it is not needed for todays update so i doubt it can be very problematic for anyone lol.)

**Comment by jewbmx** [comment]
Shit i forgot to update the little note i have in the changelog twice now for advised disabled scrapers lol.
Fast32 and 0123putlocker are both slow and should be disabled if not needed/used. Personally i just have them, library, and filepursuit disabled but imma lil loonie
