### ISSUE TITLE
Scrubs Fanart

### ISSUE THREAD

**Issue by JayDigg** [jewbmx/repo#19]
What happened to the Fanart? No fanart is showing for anything in Scrubs2. Tested 17.6 and 18. Tried own api keys also. Still no fanart. Any idea? Thanks.

**Comment by jewbmx** [comment]
I usually have the fanart option off but its most like a error on my end that i fixed earlier today. Last update i switched some code out for older versions and didnt finish updating it till today. I'll push an update tonight and see if your still having problems tomorrow

**Comment by JayDigg** [comment]
Thanks for the quick response, I tested the 4.3.3 you just put up but still has no fanart. Tested on a fresh install with 4.4.3 zip.

**Comment by JayDigg** [comment]
Ohhhh, nevermind. I just saw the "Enable fanart" button and its working. Thanks bro. Love the addon!

**Comment by jewbmx** [comment]
Shit you had me opening it back up to check for any more errors lmao. I should probably move that setting slightly so it can be spotted easier. I disabled it because the addon runs faster for me with it off.

**Comment by JayDigg** [comment]
Lol, sorry. All good now! I love the user lists you have in there btw. Nice job.

**Comment by JayDigg** [comment]
Got rid of that one click Documentary section you had in there huh?

**Comment by jewbmx** [comment]
If your talking about the documentary plugin, yea it was giving errors and as far as i know the resolver for part of it has been messing up anyways. Didnt ever find much worth watching in it either so it was a tearless delete lol.

**Comment by JayDigg** [comment]
Cool.
