### ISSUE TITLE
Music Choice Not Working

### ISSUE THREAD

**Issue by stevesawyer1338** [jewbmx/repo#2]
Music Choice add-on has quit working and wanted to see if you would fix it. It is my favorite music add-on was working great and now when you click on a channel the blue play symbol shows up but then it stops. Please fix!!!!!!! Thank you

**Comment by jewbmx** [comment]
Those links went down a while ago lol, either a well needed site update or they just patched the leak. So as far as i can tell, the only way to fix it is find new links for the choices but i havent found anything yet and doubt i will lol
