### ISSUE TITLE
Source ODB

### ISSUE THREAD

**Issue by bjgood** [jewbmx/repo#2]
Hi jewbmx,
Do you get any links with source odb.py? I'm getting nada.

BTW, congrats on your kattv cfscrape solution. I tried for a couple of hours to get it up and running but never could.

Have a good one, bud. :).

**Comment by jewbmx** [comment]
Yea odb.to is 1 openload link. Test it on deadpool and a 1080p pops up

**Comment by jewbmx** [comment]
Also cant take credit for the kattv, it was emailed to me lol

**Comment by bjgood** [comment]
BTW, happy holidays to you and yours. :).
