### ISSUE TITLE
How to add other source to your scraper?

### ISSUE THREAD

**Issue by xXHexaKillXx** [jewbmx/repo#20]
I would like to add some Asain Dub TV shows and movies sites to the scrapper?

**Comment by xXHexaKillXx** [comment]
https://phimbo.us and https://phim33.tv are the sites i would like your scrape to scrape these show if this can be done or not?

**Comment by jewbmx** [comment]
Sure i will get into it soon. You wanna toss me a few item examples? Like...
(Movie - year)  or  (TvShow-season-episode)

**Comment by xXHexaKillXx** [comment]
sure  do you want me to link those base on the two site i mention?

**Comment by xXHexaKillXx** [comment]
do you have like a template i could use so that it is easier for you?

**Comment by xXHexaKillXx** [comment]
https://phimbolongtieng.com
https://motchill.tv/phim-moi/?order=&genre=18&country=&year=
https://otvhay.org/z.php?PL=Phim-Bo

here are the other site recommend.

**Comment by jewbmx** [comment]
Ive looked into a couple of your site choices and they are non-english ones which apparently also have normal english movies in that language lol.
This kinda stuff is best left to a dev that uses this language so i will not be touching any of it.
My addon is pretty much for English only and gonna stay that way lol. (I ditched all the other language support stuff long ago and quite happy i did.)
