### ISSUE TITLE
Scrubs V2 source launch failure

### ISSUE THREAD

**Issue by pghenry** [jewbmx/repo#22]
Hi Jewbmx,

I'm using diggz 2.0 build with Scrubs V2. I like the auto launch of the provider stream but lately the stream choice fails and there is no option to select another. Is there a work around to try additional provider streams?
Thanks,
Patrick

**Comment by jewbmx** [comment]
Im guessing your one of them fools that is using the auto-play feature and thats what your talking about here lol.
Easy answer is stop being a fool and use the default setting as its the best one lol. This is free sources not debrid shit which means sources get removed constantly and are bound to fail 😉
Your only real alternative is to disable scrapers of hosts which you find to fail often or maybe sort the list differently to make more viable ones be at the top.

**Comment by pghenry** [comment]
I didn't enable the auto-play feature. It was that way with the diggz
build. I tried to disable the auto-play feature but didn't work. I figured
it out and removed the provider that was failing.

Thanks for the quick response.

Patrick

**Comment by jewbmx** [comment]
Well theres your real problem 😀 your using a build lol
