### ISSUE TITLE
Is this the best place to suggest new sources for scrubs v2?

### ISSUE THREAD

**Issue by ilikenwf** [jewbmx/repo#23]
Found a site that uses some weird obfuscation that so far I've only managed to get working using selenium, but it has so far had a show before the other sources it uses did.

js2py freezes trying to use their js...

The site: bstsrs(dot)one
removed

**Comment by jewbmx** [comment]
Well i personally like this kinda stuff in a email away from prying eyes that stalk the internet lol but another alternative is just to dummy up the urls so they cant be found as easily :) like {https://}google{dot}com/sucks.

But yea i can have that scraper made in a couple minutes,  the code used to decode it is actually similar to the cleangenre type of modules we use or the cleanhtmlcodes which has a code like ['47ab07ec': '4',  '47ab07ea': '2', '47ab07e8': '0'] and a basic .replace ran on it.  Ive seen sitting on it for quite some time in my unused modules folder. Originally someone tossed it to me for another site but the site died off a few weeks later before i ever got to it lol.

**Comment by ilikenwf** [comment]
Ah, nice. Assuming that you have the URL in your github notification, I can edit it here...

Thanks for looking at this...I didn't feel like reversing the scripts as I'm lazy tonight so I kinda just half assed it by tossing it into gpt...

**Comment by jewbmx** [comment]
sorry im way too high tonight/tismorning and didnt notice your reply then forgot why i made that  scraper lol. just been chillin here watching the tomb raider movies and making scrapers :)

if your tech savy enough here is the scraper you requested, and no matter your skill level i tossed a simple readme.text in the zip file that shows you where to put what lol.
https://github.com/jewbmx/temp_space/raw/main/bstsrs_one.zip

**Comment by jewbmx** [comment]
sadly i couldnt figure out a way to use their search function so i then tried to bing it but them results were shitty and inconsistant so i resorted to just making the url by hand in 2 styles that i noticed while in the code which is just a with year then without if the with fails. also added a imdb check to ensure the page is correct.

**Comment by ilikenwf** [comment]
Very nice of you to do all that, want me to test it out locally? I'm not even sure where the scrubs v2 code is hosted, if it is publicly.

**Comment by ilikenwf** [comment]
...I didn't think about using a table for the encryption, nice.

**Comment by ilikenwf** [comment]
I added it to the proper directories and added the config line enabling it, cleared the caches, but it does not appear to work if I only enable it as a source...even with others enabled it appears that the links aren't being scraped from bstrs.

**Comment by ilikenwf** [comment]
Oh...I mistyped the name in the config.

**Comment by ilikenwf** [comment]
Despite that it doesn't seem to be showing in the results list, wondering if despite clearing the caches and such I missed something?

The code looks good and decrypt works manually, so I'm wondering if I'm running into something weird with kodi itself...I also tried disabling dupe filtering with no luck.

**Comment by jewbmx** [comment]
Ive done a little more tinkering while buttoning up that scraper and some others i made so im not sure what might cause ya problems. 
Basically you could of dropped then files into the addon where they belong and it should of worked right on the first search attempt. You could also "right click" in the movie or episode list and click the clear sources option to make the source search be fresh. Settings wise they are only needed to disable a scraper, the scraper runs with or without the setting. 

Imma go ahead and update the addon in a little bit tho so you dont gotta worry about any of it lol.
I just tossed you the zipfile incase you wanted it for something else or didnt wanna wait for a update.

**Comment by ilikenwf** [comment]
As it turns out Kodi had failed to update your repo for some reason, so fixing that got me several versions ahead...

**Comment by ilikenwf** [comment]
Even if I enable only bstrs, now, I get "no stream available" so something may still not be quite right.

**Comment by jewbmx** [comment]
Should be v5.1.33 if i recall. Might need to clear all cache in scrubs and maybe even in a cleaner like kcleaner lol. If none of that helps i dont know what ya did or what your lookin for but id try to change something up.
