### ISSUE TITLE
Scrapers not scraping?

### ISSUE THREAD

**Issue by JaxJoe01** [jewbmx/repo#23]
Last 2 weeks have gone from 100+ links for shows down to 4-10 if lucky.  Does Scrubsv2 use resolveurl or other backend for scraping?  I thought SV2 used its own.  Asking as the followup is if you have any info on modifying them etc, will gladly poke and help about if needed.

**Comment by jewbmx** [comment]
Scrubs uses resolveurl. A few resolvers are not working but doesnt really effect your search. I been ditching scrapers i dislike and dont wanna maintain anymore so that is one reason why your count is depleting, there is also some cloudflare(cfscrape) changes that cause some issues but thats mostly resolved now besides a few scrapers still in the temp folder i have set aside for tests or edits.

You might wanna clear your cache and providers in the tools menu and see if your results improve. If you still have conflicts you can enable some spares too, or list a couple scrapers you used to enjoy and i can look into em and try getting ya happy.

**Comment by JaxJoe01** [comment]
Just a followup as I have done more digging. . . 

I am mainly concerned about real-debrid links.  RLSBB would usually provide tons of links paid or not now there is none.  But I went through the setting and RLSBB is there.  So my assumption is this is not of your fault but is based off of the resolveurl settings...  I guess that is the majority of the problem because hit shows are coming up with minimal returns for debrid and normal results.

I guess it's time to put kodi on my pc and start debugging the hell out of it  haha   Yeah, definitely not a cache or provider problem.  Just debrid results have gone down to nothing for hit shows so was hoping a quick pop in here to you (Because your addon and backend support you do for your addon is top notch btw) would see if any of the scraping you setup went south in some way.  Thanks for the quick follow up!

**Comment by jewbmx** [comment]
I'll run some tests and see whats up today.

**Comment by jewbmx** [comment]
I added another rlsbb scraper that should solve your problems for now. Just disable the normal one and enable rlsb. Should have the update available in a few minutes. I will leave this issue open for the night incase ya need it. But think you should be ok now.

**Comment by JaxJoe01** [comment]
Thanks, will try shortly!  Side note... Tried to install SV2 on my windows on a clean install and the following modules are missing from the repo so cannot be straight installed.  Added all addition repos listed in your base as well: (From repo info @ github.io, not repo.cf as that one looks to be shut down)

script.module.beautifulsoup4
script.module.dateutil
script.module.futures
plugin.video.youtube
script.module.python.twitch
script.module.cryptopy
plugin.video.gdrive
script.module.simplejson
script.module.addon.common
script.module.myconnpy

**Comment by jewbmx** [comment]
Install the repos that are in my repo and you shouldnt have any problems.

**Comment by JaxJoe01** [comment]
I am saying that was done... And the above are modules / plugins still unavailable.  Using latest18.1 release, installed new, added your io file path, installed your primary and backup repo, added all repos avail through your repo and the list above is what comes back as unavail when trying to install SV2.  I can get them installed but the process above = no scrubv2 install.

**Comment by JaxJoe01** [comment]
Scratch that, just tried again and mashique.... hrumph...  You messing with me now?  lol

**Comment by jewbmx** [comment]
Not sure why that would happen, most that list looks to be the default kodi repo items. Might of been a glitch like installing while the update was being processed.

**Comment by JaxJoe01** [comment]
Just FYI... when the windows version detected the new sv2 4.3.9, installed just fine.  Being as I am a creature of habit and never look at a golden goose... On my mecool box I checked the settings for my repo.  It still had the old information as repo.cf.  Changed it to github and then checked for updates... 4.3.9 came right in.  I did check on my working box where the missing items existed and they were all in the Kodi Add-on repository which was part of your addt'l repo's.  </blank_stare>  No clue

There is something funky going on with resolvers and I am not sure where the culprit lies.  I will do some more debugging.  But as to a followup with your modifying rslb... I disabled the rslbb, enabled the rslb and sure enough a ton of debrid links showed up for that scraper for 2 shows tested. 

Just so you know my baseline of testing:
Only SV2 addon on all devices (been that way for 3+months)
Show premium sources / results only (Paid for it - tired of horrible free links)
Max Quality - 480p
Default Action - Autoplay
Providers - Enable all normal providers  (Disabled 123123movies and 123movieshubz atm for slow links)
Spare Providers - Enable All Debrid Providers

Disabled - Spare Providers
     -  English---Disliked/sloppy (Bulky or Captcha Results)
              - All foreign providers (Because yeah)
              - All torrent     (Without VPN could be a bad thing in the universe)

Enabled
- Trakt
- Real-Debrid

Additional disabled note...  A few days ago - a week ago, something happened but I didn't have anything setup on my boxes to figure it out where I did have some foreign and I did have some of the sloppy enabled however when clicking a show or a movie, it looked like the result box was frozen and then disappeared.  One or more of the scrapers was causing this and simply disabling all (Didn't have time for trial and error) cause the results to function as normal.

Sorry for the lengthy post to the original post of not many links anymore but just hope to add info to support you.  I will go back and troubleshoot - find out which scrapers caused an issue and post a new article if found.  Thank you for such great support!

**Comment by jewbmx** [comment]
Gonna close this now but, You can use the torrent support without worry and you will probably like it too depending on the item, Just set your dbird account to cached only in resolveurl to prevent the spare popups and have easier time. Its been tested pretty good without vpn trash.

Also you should go ahead and pick thru the spare tires one by one because there is a few goodies tucked in there now.
