### ISSUE TITLE
Chat of June & July 2019 #Lazy lol

### ISSUE THREAD

**Issue by jewbmx** [jewbmx/repo#26]
Puttin together a little updated url list this week to clean up my phone a bit so i'll toss it on here too.

Anyone able to say entervideo and megamp4 hosts work for em recently?

**Comment by jewbmx** [comment]
Im too stoned and lazy right now to open my email lol but you will probably see it just as fast here. This is what i get from a test run on coolmoviezone

Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.scrubsv2/lib/resources/lib/sources/en/mycoolmoviezone.py", line 33, in sources
    r = self.scraper.get(url).content
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.scrubsv2/lib/resources/lib/modules/cfscrape.py", line 157, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.scrubsv2/lib/resources/lib/modules/cfscrape.py", line 205, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.scrubsv2/lib/resources/lib/modules/cfscrape.py", line 145, in request
    raise Exception(exception_message)
Exception: Cloudflare returned captcha!

**Comment by weekendsource** [comment]
Regular cloudflare here, must be geo/ip targeted recaptcha.

**Comment by jewbmx** [comment]
I got a email back from the person i was talking to that pretty much says the same without the words lol. I think its just a error in the cfscrape version i have. Gonna swap it out today and run a few tests.

**Comment by bjgood** [comment]
Both entervideo and megamp4 work for me (in the movies section). And, coolmoviezone works in the movies section with the cfscrape version you have in scrubsv2. I tried both Avengers: Endgame, and Aladdin.

I also have a cfscrape version that I found in eggman's repo from script.module.overeasy that's slightly different than the one you use.

I see your posts are 17 hours old, so maybe everything is alright on your end now.

**Comment by jewbmx** [comment]
Anyone ever have a full system freeze type of crash around 1:15:00 or 1:30:00? Think ive seen it twice now both on items that were 2hrs long or more lol. Also spotted some dialogbusy errors for script.extendedinfo but it could be a fluke since i dont use that crap lmao.

**Comment by jewbmx** [comment]
Havent bothered with it yet but looks like cartoonwire is now replaced by  watchcartoononline.info

**Comment by jewbmx** [comment]
Trakt api url is now https if anyone hasnt spotted it, also if you spot a dead host get ahold of me and i'll look into it.
Heres the list of already checked and blocked ['waaw.tv', 'netu.tv', 'movdivx.com', 'divxme.com', 'streamflv.com', 'speedvid.net']

**Comment by jewbmx** [comment]
Looks like a few scrapers cant be improved to be more accurate without adding a second page hit, so it begs the question to have a working but half shitty scraper or make it a good scraper that is twice as likely to get broke.

**Comment by jewbmx** [comment]
Disable mycoolmoviezone if ya see this lol, took the time to get it going without issues and now the site went to shit again lol. Next weeks update will remove that trash ass pos for good.

**Comment by bjgood** [comment]
Thanks for the update, bud. :).

**Comment by jewbmx** [comment]
Damn i just noticed universal scrapers is still dead in the water lol. I even handed off a decent sized update for it over a month ago to help it stay afloat that never made its way.

**Comment by jewbmx** [comment]
Came across another way to do a valid check today that i never tried before.

import resolveurl
if resolveurl.HostedMediaFile(link):
(Dent)[shit]

**Comment by weekendsource** [comment]
It's nice to see you :)

**Comment by weekendsource** [comment]
You are the cutting edge, keeping much of the stuff alive, respect for that.

**Comment by jewbmx** [comment]
I just try to keep my addons working good for me and the extra imports that impact that lol.

**Comment by jewbmx** [comment]
While im thinking of imports i gotta trace down what addons i got on my phone using the open scrapers module so i can ditch that shit. I aint waiting 5 mins for all those imports they decided to add in

**Comment by jewbmx** [comment]
Anybody that uses UniScrapers feel like doing a couple test runs? My last update made the module run fast and smooth for all my devices, and im a little curious on if anyone else sees a difference lol

**Comment by jewbmx** [comment]
Love when i pause my movie before falling asleep to wake up later and see the last 4 seconds before the credits start rollin. 

Got a couple emails saying uni runs better now like i thought, and mr jim has tested far enough to also spot some scraper problems i gotta look into. Imma finish my current project and bounce back to uniscrapers soon for a version C update fixing/testing scrapers more, so if anyone has something to add to it there will be a uniscrape repo tossed up on my account for it. (Might make it a perm. thing)

**Comment by jewbmx** [comment]
Anyone got some easy ways to use year in the def sources even tho it isnt used anywhere in the scraper? A good example would be 1putlocker.io

Scraper goes url + '/aquaman/'
Then grabs <iframes

Im thinkin about adding this as a first step before <iframes with/as a year check.

yearcheck = re.compile('<strong>Release: </strong> <a href=.+? rel="tag">(.+?)</a>').findall(r)

**Comment by bjgood** [comment]
Hey Jewbmx,
It's been a while since you updated Scrubs. Lost interest in exodus type  scrapers?

You've been awfully quiet here of late.

**Comment by weekendsource** [comment]
According to latest cloudscraper commit, ciphers in cfscrape line 122 should be:

```
        if hasattr(ssl, 'PROTOCOL_TLS'):
            ciphers = [
                'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-CHACHA20-POLY1305-SHA256',
                'ECDHE-RSA-CHACHA20-POLY1305-SHA256', 'ECDHE-RSA-AES128-CBC-SHA', 'ECDHE-RSA-AES256-CBC-SHA',
                'RSA-AES128-GCM-SHA256', 'RSA-AES256-GCM-SHA384', 'ECDHE-RSA-AES128-GCM-SHA256',
                'RSA-AES256-SHA', '3DES-EDE-CBC'
            ]
```
No 503s :)

**Comment by jewbmx** [comment]
Just got back online finally lol. you wanting me to remove the cipher code you dont have in that bit? Took a quick look and the mod i am using has em all and a couple more in it.

**Comment by weekendsource** [comment]
Yes, look at the latest commit in VeNomouS/cloudscraper. It says "Cloudflare triggering reCapthca on the cipher ECDHE-ECDSA-AES256-GCM-SHA384", and it's true, it does ;)

**Comment by jewbmx** [comment]
This is off topic and not meant to sound rude, but anyone that emails me or contacts me in any other ways should stick to proper subjects and not waste their time trying to make "small talk" with me as i dont bother with it. Also stick to one email or chatbox instead of sending a new one every time. I keep a pretty active email conversation going with Tempest and we rarely need to make a fresh email when you can simply hit reply and clear the old shit out of the message lol.  This post might explain why some people might not get a response from me ;)

**Comment by jewbmx** [comment]
Not sure if host505 still looks at these little issue chats but there seems to be some kinda hidden error in his 1337x scraper. I checked it out because it was said to be faster then the normal one and it really is, but when you goto clear sources the scraper causes a odd lagg delay that i have yet to traceback and find lol. Tried checking imports and some edits so imma try lil shit like adding a dummy self.base_link next.

**Comment by host505** [comment]
Not 'my' scraper (not sure of it's origination, hence the missing header/credits), but I don't have any lag/delay on providers cache clearance.

**Comment by jewbmx** [comment]
I use my laptop for average user use and my s7 droid phone for dev use and both usually work the same for me and my addon. Phones a little slower but thats probably because of settings and content lol. Tried that scraper on both with devices with and without my edits but both had the same bug. When i try it thru your addon its all good, and in Tempest i get the issue again lol. The 1337x scraper i already use is broke for me too but might try to fix it later today and just add in a bit of the search differences and see if that makes a change once its working again.

My highs always getting snuffed out by dbird shit lol

**Comment by jewbmx** [comment]
That 1337x maze is over now lol i just ghetto rigged 3 scraper versions together and tossed in my little edits. By itself on a quick test it only takes to 4% before it loads the results and issue free.

**Comment by bjgood** [comment]
> This is off topic and not meant to sound rude, but anyone that emails me or contacts me in any other ways should stick to proper subjects and not waste their time trying to make "small talk" with me as i dont bother with it. Also stick to one email or chatbox instead of sending a new one every time. I keep a pretty active email conversation going with Tempest and we rarely need to make a fresh email when you can simply hit reply and clear the old shit out of the message lol. This post might explain why some people might not get a response from me ;)

Guess we all know who that statement was aimed at. ->Me.

Later, dude.

**Comment by jewbmx** [comment]
Thats aimed at no one and you bypassed the first sentence you lil drama slut lol
I figured if anyone was gonna take offense to it, itd be 3 of the main email people that send me atleast 1 a week lmao

**Comment by bjgood** [comment]
Since you stopped responding to any of my posts I figured it was me. A natural assumption on my part since you are basically an asshole. You use to a friendly asshole. What happened to you? Maybe doko was right. You are a drama queen! ;).

Later...

**Comment by jewbmx** [comment]
Ran into a funny new url a min ago while fixin up cartooncrazy  https://123movies.gostreams.net/  lol

**Comment by jewbmx** [comment]
Any cfscrape pros feel like updating this?

https://gist.github.com/jewbmx/f11a75cf961147a07aba1cd061eed66d#file-cloudflare-py

**Comment by bjgood** [comment]
Gorillavid, movpod, and daclips are down. Have been for the past two days.

**Comment by jewbmx** [comment]
Found another odd site http://www.tv.com/shows/greys-anatomy/watch/

**Comment by jewbmx** [comment]
Damn cartooncrazy is crazy lol ive been updating the same plugin/source for over 6 hours. Made 1 small typo that turned it into a super lagg switch lol that ate my phone so quick that it froze kodi in seconds and the entire phone lmao, had to unplug and let it overheat to his drained death and recharge it just to get it to stop. Afterwords required a kodi data wipe to get it open again too with a quick addon folder move and restore. Now to laugh a lil more im high as hell so i got to rinse and repeat because i forgot to fix it before hopping right back to a test run.

**Comment by jewbmx** [comment]
Got bored and tried out host505's new torrent codechange and it looks like its working.
Did the sourcesDialog bit and then tossed the rest in as this to be lazy..
`                    try: offset = 60 * 2 if items[i].get('source') in self.hostcapDict else 0
                    except: pass
                    try: offset = float('inf') if items[i].get('source').lower() == 'torrent' else 0
                    except: pass`
Id have to toss it to my laptop to do a really good testrun but think it works just as good.

Might be wrong tho lol that module gets me lost alot.

**Comment by host505** [comment]
Yeah wanted to discuss about that.
In case someone doesn't know what we're talking about: the problem I was trying to solve is that when you're trying to play a torr link but it's not cached to your debrid service, a resolveurl dialog pops up and tries to transfer the video file of that torr to the debrid services cloud.
But, Exodus code has a link skipping function, meaning if a stream takes too long to start it skips it and moves on to the next. So happens here, so the caching process never works.

I tried to solve it this way: https://github.com/host505/plugin.video.theoath/commit/73de313d0f49ef717b765d07d491ee0e14bfcaba
It's briefly tested though, and only through Rd, and I consider it a bit hacky, maybe someone smarter has a better idea.

@jewbmx I see you excluded the part that I check for the resolveurl "cached only" setting, I think that means that if a user has "cached only" set to true on resolveurl, it won't skip uncached torrents. Not tested though.

**Comment by jewbmx** [comment]
I was thinking the way i put it in makes any/all torrent result act the same way which in my head its try,wait,play. But thats based off the little i know about float () lol. If i recall float with inf means take as long as you need but finish asap.

I also tested that code as this but im pretty sure this makes all the pairing hosts just sit there when ya want them to skip on if your like walking around doing a dab while your waiting for the flick to start lol.
`offset = float('inf') if items[i].get('source') in self.hostcapDict or items[i].get('source').lower() == 'torrent' else 0`
Lazy 1 line'R but not a good one

**Comment by host505** [comment]
Nope, float('inf') means infinity! Meaning that I let the caching process take as long as it needs to, unless I manually cancel it. From my tests, when it finishes caching it starts to play.
So, not a good idea to also apply it on captcha hosters. There it's set to 60 * 2, I think to match resolveurl's timeout.

**Comment by jewbmx** [comment]
Lol how you gonna say nope then say the same thing with different wording :p

Im leaving craptcha as it is but had to try it out for the sake of curiosity lol. I dont really use anything except for the free normal scrapers so i might leave the 2 line version in for a update and see what its like on my laptop for a torr day.

Ya might think its hackish but i think its beautiful lmao, every time i try thinking of a fix for that ive always wound up stumpt. Thats simple and a success ;)

**Comment by host505** [comment]
Yea been thinking of it too long myself too, I was thinking of ways to identify when resolveurl's window is visible via condVisibility, but not any resolveurl window, eg not the pair one.
Then I saw the offset code and it got me.
Nope was for the 'take as long as you need but finish asap' you said, confused me a bit. It's just plain infinity.

**Comment by jewbmx** [comment]
Your thinking of it in only one way of usage lol im pretty sure theres more to it for other imp's.

**Comment by host505** [comment]
Yea didn't want to change any other behavior, the pair system or anything, just wanted to fix that torr caching thing.
Whether this inf bit will be useful for other cases, don't know, maybe, what do you have in mind?

**Comment by jewbmx** [comment]
Oh nah i dont got more ideas for using it lol i was still talkin infinity.

**Comment by jewbmx** [comment]
I typed it into my laptop and did a few tests on it with and without cached-only enabled and its all good. Even ditched adding the try:except:pass shit to be sure

**Comment by host505** [comment]
It finished caching and failed to play, or failed caching and moved on to the next?

**Comment by jewbmx** [comment]
My bad forced myself to sleep so i could ditch a headache lol. Not sure which but if it failed caching then it was towards the end because it was going along just fine beforehand lol. If i see it again ill save my log and trace it back.
That reminds me that i gotta add some form of a debug log wipe option for the addons log, thing gets big lol

**Comment by jewbmx** [comment]
Need that 1337x search for all torrent sites lol that seeder bit is useful. You can try Ugly Dolls it had mostly all uncached a couple days ago. Its newish and a little rare.

**Comment by jewbmx** [comment]
If anybody has resolveurl settings shortcuts added to their addons you probably need to double check em and update em. Havent bothered yet but its probably 6.0 needs to be 7.0 ..

**Comment by jewbmx** [comment]
Lmao check out this cartoon websites source. Straight from the page, and every other source is good lol.

`<a href="#" rel="29" data-video="https://www.xstreamcdn.com/v/">Xstreamcdn<span>Choose this server</span></a>`

**Comment by jewbmx** [comment]
Anybody know why b98 aka b99 isnt playing anymore? Example url would be http://www.b98.tv/video/A-Scooby-Doo-Valentine.mp4
Used to play fine in kodi and now its got me stumpt lol

**Comment by host505** [comment]
@jewbmx you have to add the offset definition on sourcesDialog as well. I saw you added '+ offset' there but you didn't define what the offset is, which broke Dialog source selection.

**Comment by jewbmx** [comment]
Yea i found that out the hard way yesterday when i was making a scraper and trying to be lazy lol. Took around a hour to figure out what and where lmao.

**Comment by host505** [comment]
I don't know why it didn't have the offset for the captchas before thought, was it skipping them?
I never use the dialog source selection so haven't noticed.

**Comment by jewbmx** [comment]
I dont use either but in most cases the craptcha/pair usually moved on before it should. Pair a vev.io and wind up on a openloaf

**Comment by jewbmx** [comment]
crazy4tv.com is back up and running if anybody wants to fix it, pages are simple but its dbird.

**Comment by weekendsource** [comment]
https://pastebin.com/dfN36umJ cfscrape.py fixed according to the latest (1.1.25) VeNoMous cloudscraper.

**Comment by jewbmx** [comment]
Thanks.  Im still working on getting the old one updated i posted in a gist thats used in cartooncrazy for cookies lol. Gotta try it on my laptop tho because my phone is too much of a hastle.

**Comment by weekendsource** [comment]
A good thing about this one is that it's pure python without js2py or heaven forbid ;) node.js. It should fetch you cookies too :)

**Comment by jewbmx** [comment]
Seen that as i was getting it pasted :) im about to just update the getHTML def if it doesnt do the trick lol.
Im hoping this cfscrape you just tossed will make my scraper run better too, spent 2 hours making it because its a cunt and also had cfscrape errors randomly like cypher problems lol. The 1 scraper was taking upto a slow 48% just to get 5-7 results

**Comment by jewbmx** [comment]
My nets too slow and drowned down today so i gotta wait till tonight to test that cfscrape more and work on scrapers lol. Tossed it in and did a quick test run tho since i was needing to update, didnt have it ding my debug at all so it is doin good. Been keeping the previous version upto date when noticed too and saved it as a spare backup.

**Comment by jewbmx** [comment]
Can add that gay ass Telegram app to the list of ways to reach me lol. A buddy finally forced me to install it, Names @JewBMX i think.

**Comment by jewbmx** [comment]
Time to double check the 123 hubz and 123123 scraper base again aka fmovies and so on. Resolve def is broken yet again lol. Dont even wanna admit how many things i just checked before noticing lmao

**Comment by jewbmx** [comment]
Wanna see something funny. Open a scraper or whatever and goto the find/replace option and use `find: \n replacewith: .+?` . click the find/replace button a couple times to see the next one found lol. Felt lazy and tried it on my phone and my quickedit pro regisiters it as its purpose lol finding me all the next lines instead of the \ n i was wanting to replace. Glad i didnt hit replace all

**Comment by weekendsource** [comment]
Check keybase messages

**Comment by jewbmx** [comment]
Doin it now. My bad was testing code in kodi and didnt see the notifications

**Comment by bjgood** [comment]
If you get some spare time, Jewbmx, have a look at resolvers estream, vidtodo, and rapidvideo. None of them seem to be working. You are good at getting resolvers going again.

Gorillavid (the site) is down again, as I'm sure you know. Hope we don't lose it. It's one of the best.

Later, dude.

**Comment by jewbmx** [comment]
Theres 2 reasons why imma say no bj ;) 
First is because your probably clicking sources from the scrapers i said need the resolve def fixed. Second is because you need to wait atleast a week before reporting faulty resolvers lol. Im watching a rapidvid right now so i know its fine :-* so i kinda just looked into it lmao

**Comment by jewbmx** [comment]
Got a email saying the new cfscrape isnt kodi 17 compatible.

**Comment by bjgood** [comment]
> Try what you was having issues with sometime today when your on and let me know.

Well, if vidtodo, estream, and rapidvideo are working for you then no point discussing it. I tried both movies and TV series (probably nothing that you would watch...there's no blood and gore, nor over weight vombies) and they just don't work for me. In fact it skips right on by them.

C'est la vie.

Have a good one.

**Comment by jewbmx** [comment]
Whats your kodi v?

**Comment by bjgood** [comment]
> Whats your kodi v?

Kodi 18.3 (the latest). LibreELEC 9.2 Alpha 1. RPi 3.

**Comment by jewbmx** [comment]
You clear cache and providers? Maybe even click the resolver clear too lol

**Comment by bjgood** [comment]
Yeah, I clear the cache and providers frequently. No, I haven't cleared the resolver. I'll do it now.

**Comment by jewbmx** [comment]
Anyone wanna try loading either of these in a browser? My nets either bogged down or they are bad lol

http://www.animenova.org/
http://www.anime44.com/

**Comment by weekendsource** [comment]
They are bad, timeout on both

**Comment by jewbmx** [comment]
K i can delete em from my list then lol.

**Comment by jewbmx** [comment]
Man i need a addon for PM to search a movie like i do in scrubs then do that stupid torrent cache for all the results lol. So boring waiting for 80 720p and sd results to fail just for the peice of shit 1080p ones to load up instead

**Comment by host505** [comment]
You mean to do torr cache check? Been fidlin with that idea for some time now, with Rd though (don't have pm), but to no avail atm.

**Comment by jewbmx** [comment]
Its kind of annoying but luckily i only use dbird for stuff that has no valid results lol. Imma just use my phone and prep the files on the site and hopefully scrubs picks em lol

**Comment by jewbmx** [comment]
Van Damme Day is being ruined by poor sources :(

**Comment by jewbmx** [comment]
Apologies for floodin everyones feeds with my repo cleanups lol, got a little bored and the mess was bugging me. R.I.P. to the stuff i ditched, everyone can feel free to curb hop the shit out of it lol

**Comment by jewbmx** [comment]
Might be too high when you spend an hour writing a scraper just to find that you already made the same one yesterday.

**Comment by bjgood** [comment]
> Might be too high when you spend an hour writing a scraper just to find that you already made the same one yesterday.

Doesn't surprise me with the stuff you watch. Van Damme!? Give me a break. His stuff rots your brain. Thus explaining your repeat performance. ;).

**Comment by weekendsource** [comment]
Jean Claude Van Damme are great. I watch all four of them ;)

**Comment by jewbmx** [comment]
first word in ignorance is ignor, (the e is so silent that ya dont even see it) ;)

**Comment by jewbmx** [comment]
who wants to ring in on a vote? anime site being scraped as dub, sub, or one of each and let ya enable the one ya want lol.

**Comment by bjgood** [comment]
Hey Jewbmx,
See if you can make a scraper for this site...

https://www5.two-movies.name

It appears to be a really good site for TV series.

**Comment by jewbmx** [comment]
Nope you dogged the damme, your dead to me

**Comment by bjgood** [comment]
You're joking, right? I hope so at least. Besides, after further investigation the link I provided pretty much sucks. I was responding to say forget I mentioned it.

If you're joking you better say so. Otherwise, I won't be coming back here again.

**Comment by jewbmx** [comment]
Doubtful lol, you would allow such sweet serenity bj lmao.


Anyone wanna test this cfscrape?
Should solve the little bugs if its done right lol

https://raw.githubusercontent.com/jewbmx/ScrapeScraps/master/cfscrape.py

**Comment by bjgood** [comment]
I've had enough.

Later, Jewbmx. It has been fun at times.

**Comment by Bidillu** [comment]
![image](https://user-images.githubusercontent.com/49745333/60875505-4de27380-a23a-11e9-9a1f-6f384d167ec1.png)
This should put me in the boss' good books

**Comment by jewbmx** [comment]
anyone gets bored they can test this one out in their device or figure out if its able to be  used with more scraped lol. i dont really care either way lol the site its from is more like a anime trakt anyways lol

`<iframe src="https://www.crunchyroll.com/affiliate_iframeplayer?aff=af-44915-aeey&media_id=588346&video_format=106&video_quality=60&auto_play=1" width="720" height="480" frameborder="0" allowfullscreen="true"></iframe>
`

**Comment by jewbmx** [comment]
Ditched my last post because i just uploaded a updated toon/anime url list lol. Im done with them for a long while now. Spent the last week or so knocking the list down and made enough lol.

**Comment by jewbmx** [comment]
Since i seem to have a surprising 40+ people following me on here imma ask ya all a question in hopes that one has the answer lmao..

Anyone have a search.xml file that is for the lists indexer i am using in scrubs? Previous addons ya might know that use the same indexer/code would be like phstreams or jizzplanet.

Gameplans to make the search feature work or make one. Example search would be looking for NOOB in all the temptv xml files lol.

**Comment by jewbmx** [comment]
gonna use this emailed url as an example for this lol
any sources you get as results labeled vidtodo are likely erroring from this.

first url:
http://vidtodo.com/apu123hwvg7c
- uses cloudflare now then redirects to...

https://vidtodu.com/apu123hwvg7c
- not yet in a legit update so your on hold lol.

another domain is...
https://vidtodoo.com/apu123hwvg7c
- still works but is behind cloudflare too.

**Comment by jewbmx** [comment]
Ahh when your too lazy to try and scrape quality :)

`

    def sources(self, url, hostDict, hostprDict):
        try:
            sources = []
            r = self.scraper.get(url).content
            match = re.compile('<iframe.+?src="(.+?)"').findall(r)
            for url in match:
                if not 'youtube' in url:
                    quality = '720p'
                    info = 'or 1080p'
                    valid, host = source_utils.is_host_valid(url, hostDict)
                    sources.append({'source': host, 'quality': quality, 'language': 'en', 'url': url, 'info': info, 'direct': False, 'debridonly': False})
            return sources
        except:
            return sources
`

**Comment by jewbmx** [comment]
[Puts door not disturb sign on door.] 3Below Seaon 2 just dropped yeah!!!

**Comment by jewbmx** [comment]
Ever wonder what a subtitles file might look like? Lol

https://vidcloud.icu/player/sub/index.php?id=L2VsZW1lbnRhcnktc2Vhc29uLTctZXBpc29kZS04LW1pc3MtdW5kZXJzdG9vZC9lbGVtZW50YXJ5LXNlYXNvbi03LWVwaXNvZGUtOC1taXNzLXVuZGVyc3Rvb2QudnR0
