### ISSUE TITLE
Music Fanart for Addon

### ISSUE THREAD

**Issue by crackingbike** [jewbmx/repo#27]
hi Jewbmx ... first of all what an awesome fork and some really cool enhancements to the offerings ... Full credit for keeping the same interface navigation but the music section blew me away last night ... amaze balls !!! .. anyway, just an idea if it could be considered in your backlog to add some fanart to each song that plays just to replace the background colour that is the default .. Classic Metal ... keep up the good work a refreshing spin on the original ..ace

**Comment by jewbmx** [comment]
Im literally off the grid for about another 12 hours or so, i'll look into
it when my nets all good. Might wanna comment back once more tho and give
some more details like which addon and which music section, also the odds
of this being possible are slim depending on which section.

**Comment by crackingbike** [comment]
no problem, main reason was to give you the Kudos for a cracking Fork ... when i'm home later, i'll be more specific for the menu position i'm talking about
