### ISSUE TITLE
POLISCH NEW  WORKING SCRAPERS

### ISSUE THREAD

**Issue by anon2018** [jewbmx/repo#28]
Please fit new POLISCH SCRAPERS from
https://github.com/anon2018/UNICORN/raw/master/zip/plugin.video.fanfilm/plugin.video.fanfilm-2019.05.23.1.zip

PS:( dont add animezone and shinden scrapers, that is working only on PL IP)

and if is possible to change sky channels to TV channels and set separate field in settings to set up EPG for scraping content

you can also try to fit play next episode for TV shows, that is inplemented in fanfilm, and think about adding up NEXT plugin compatibility for TV series from venom

**Comment by jewbmx** [comment]
I'll add the scrapers in for ya but probably gonna pass on the other suggestions.

**Comment by anon2018** [comment]
ok thx for scrapers... all exodus forks now have PL old not working one

**Comment by jewbmx** [comment]
Tossed em in, did some lite cleanup like imports, ditched the ones you said and any needing account settings, and did a little quick test. I'll update later today incase you wanna test em or use em soon while its still on our minds lol.

If ya spot any needing fixed feel free to let me know and i will load up google translate and fix whatever i can get done from the U.S.

**Comment by jewbmx** [comment]
Issue can stay active/open too for a couple days so i dont forget as easily.

**Comment by anon2018** [comment]
im waiting for update to test, and ouer FB group also:D

**Comment by anon2018** [comment]
can you make separate sattings for  switching on/off torrents/EN/EN+PL or only PL scrapers... if is like that, it wil schort time, most of ppl from PL will use torrents(debrid)+PL only, if you will make it like that it will be second or ex aequo witch fanfilm in popularity in PL...  orginaly fanfilm (reincarnation) <= Specto, is an heritage from developer MrKnow that died

**Comment by jewbmx** [comment]
Not sure what your sayin but assume ya want torr scrapers to be for each language instead of EN only. Just updated em to match the lib. scraper so its now
`self.language = ['en', 'de', 'fr', 'ko', 'pl', 'pt', 'ru']`
That should solve that problem.
 I got distracted earlier and forgot to finish so imma get that update up for everyone within the hour.

**Comment by anon2018** [comment]
sry for my bad englisch... i want to have option to set torrents + PL without normal englisch scrapers, only PL + torrents

**Comment by anon2018** [comment]
scraper update https://github.com/anon2018/UNICORN/raw/master/zip/plugin.video.fanfilm/plugin.video.fanfilm-2019.06.01.4.zip
