### ISSUE TITLE
Mighty quiet

### ISSUE THREAD

**Issue by bjgood** [jewbmx/repo#3]
Hey jewbmx,
You've been awfully quiet here lately, dude. I come here at least everyday (sometimes more than that) hoping for some updates. Are you taking a break from all this coding? Is everything alright for you? Just a little concerned.

Well, have a good one, and best wishes from me. :).

**Comment by jewbmx** [comment]
Nope nice catch, looks like that pos broke again

**Comment by jewbmx** [comment]
Fixed it, here ya go

http://jewrepo.cf/JewRepo/4git/darewatch.py

Somehow the resolve part got deleted lmao

**Comment by bjgood** [comment]
Nice work. I'll give it a try a little later.

You're a fine fellow, jewbmx.
