### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by SiWafer** [jewbmx/repo#31]
Requesting a favorites be added for TV and Movies or ability to create favorites list on demand.

Use case: A location so we can add shows / movies to a list. Single link on Kodi Favorites to get list of Scrubs Fav items

Using Super Fav is an option, but the way links are stored and played back is not great also view option is not great.

**Comment by jewbmx** [comment]
There is already the usual favorites integration plus a custom addon based one

**Comment by SiWafer** [comment]
Thanks, for some reason "My Stuff" did not show up..

Another question is, is there a way to change the default "viewtype" = "Widelist" for "My Favorites" ?

**Comment by jewbmx** [comment]
Lol my bad for the super late reply.
I personally dont use viewtype stuff so i wouldn't know altho im pretty sure the addons setup is just the use of a couple options like movies and shows then them favorites and whatnot are likely based off one of them stock options which means ya might have to change one of those to get your desired results in that section. 
I just install kodi then aeon nox silvo and my addons then rock it all pretty much stock default like a basic bitch :)
