### ISSUE TITLE
Downloads in scrubs

### ISSUE THREAD

**Issue by kenny1773** [jewbmx/repo#32]
Is there a trick to get downlosds to work in scrubs?

tools/general/special and enabled downloads and set a valid directory, click ok
found a source, right click on that source and no sub menu appears (normally I would expect a sub menu with a download option)
Thanks!

**Comment by kenny1773** [comment]
Sorry, I think I got it figured out.  I had to uninstall scrubs and delete the addon folder here
c;\users\{myuser}\appdata\roaming\kodi\addons\plugin.video.scrubs2

then reinstall scrubs and it worked
might want to leave this here as a solved issue as I saw a few other people ask in various places as I was looking for an answer

**Comment by jewbmx** [comment]
Pretty sure you just needed to clear the cache after setting up the settings lol

**Comment by kenny1773** [comment]
I tried to clear all the clear cache options I could find, didn't seem to fix it for me.  Deleting the directory dd it
Thanks for the reply, and thanks for the add-on, so far its the best I have used in years, good work!

**Comment by ghost** [comment]
Hi kenny1773, this is guappo12. I'd like to ask u if I should do the same thing. My Scrubs v2 is playing streams in a different Language, called (Libre). It changed the Audio from American to an unknown language. It happened when I changed build to Nova in kodi 21 Omega. Now, I'm using a different build. If I do the same thing, would that reverse the language to American? Please Let me know and can u tell me how to do that. Thanks Kenny1773 have a great day. Using Fire Cube 2nd Gen
