### ISSUE TITLE
Anything in the pipeline?

### ISSUE THREAD

**Issue by bjgood** [jewbmx/repo#34]
Hey JewBMX,
Any news about an update? A number of the sources have stopped working (especially TV shows).
Have a good one.
Later... 

Hope everything is alright in your world.

**Comment by Melann956** [comment]
Hi jewbmx, alot of the new shows have links but none are working.  Any idea how to resolve it? Been trying to reach you through email..Thanks.

**Comment by bjgood** [comment]
Was a bit rude of me to ask for an update from JewBMX, so, I'm closing this thread.
I'm sure, when he has the time, he'll release a new one.
Have a good one. :).

**Comment by Melann956** [comment]
We just wanted to know why the links aren't working when they were working perfectly before. 🤷‍♀️

Melissa
________________________________
