### ISSUE TITLE
Just an FYI

### ISSUE THREAD

**Issue by bjgood** [jewbmx/repo#35]
Hi,
I've been using scrubsv2-5.1.38 since it's release. I noticed I wasn't getting a lot of the sources I had under older versions. A few minutes ago I installed scrubsv2-5.1.36, just as an experiment. I now have some of the older sources back.
Just an FYI. No guarantee it will work for you.
Later... 

*scrubsv2-5.1.37 works, too.

**Comment by Thawne86** [comment]
Awesome thanks for the info @bjgood  😊

Also hope everything is well on your end @jewbmx

**Comment by ghost** [comment]
> Hi, I've been using scrubsv2-5.1.38 since it's release. I noticed I wasn't getting a lot of the sources I had under older versions. A few minutes ago I installed scrubsv2-5.1.36, just as an experiment. I now have some of the older sources back. Just an FYI. No guarantee it will work for you. Later...
> 
> *scrubsv2-5.1.37 works, too.

Awesome thanks for the info @bjgood  😊

Also hope everything is well on your end @jewbmx

**Comment by bjgood** [comment]
I also hope everything is alright, JewBMX.
Later...

**Comment by Melann956** [comment]
Hi @bjgood , Where did you find that downgraded version of scrubs?

**Comment by bjgood** [comment]
In the zips folder.

**Comment by Melann956** [comment]
Couldn't find it in the folder. Thanks anyway, @bjgood.

**Comment by Melann956** [comment]
I found the folder. The links work for me on 5.1.37. Thanks @bjgood!

Melissa
________________________________

**Comment by Thawne86** [comment]
> In the zips folder.

Just thought of something, I'm wondering if it could be possible to copy some of the recent hosters from Yonn1981's 'Matrix Addon' as @jewbmx hasn't been around for a while now & I hope that this addon isn't dead 😢

Link below;

https://github.com/Yonn1981/Repo/tree/master/repo/plugin.video.matrix/resources/hosters

**Comment by bjgood** [comment]
It's looking more and more like JewBMX has stopped development of Scrubs.
I've been using scrubs for a long time now. A long time. I shall miss using it.
Best of luck to you, JewBMX. It has been a blast.
Later...

**Comment by ghost** [comment]
> It's looking more and more like JewBMX has stopped development of Scrubs. I've been using scrubs for a long time now. A long time. I shall miss using it. Best of luck to you, JewBMX. It has been a blast. Later...

Such a shame if he has 😭
