### ISSUE TITLE
SOURCES

### ISSUE THREAD

**Issue by yugioh9** [jewbmx/repo#37]
Hi man your putlocker tv  sources aren't working agen

**Comment by Thawne86** [comment]
> Hi man your putlocker tv sources aren't working agen

Sources fail all the time, it may be the site has changed or your IP has blocked access to that certain hoster. Please be patient with @jewbmx

**Comment by Melann956** [comment]
@Thawne86 It's not just putlocker. None of the links work anymore. Some shows work but the rest don't. We're all waiting patiently...
