### ISSUE TITLE
IPTV issues

### ISSUE THREAD

**Issue by WonkyCat** [jewbmx/repo#38]
Menu
   more stuff
       IPTV
             ustvgo   is not working currently.   it's my favorite :)

**Comment by jewbmx** [comment]
Thanks for the heads up and nice post lol,  the site changed to cfscrape the other day to push us off their site and it looks like they changed it up again to some form of auth use now or a form of crapcha.

I'll mess around tonight and see if i can get it working again but i doubt it, odds are the site doesnt want kodi use which means i will be removing it completely before any "damage" is done.

**Comment by jewbmx** [comment]
Might be better to put this off for a couple days and give the website a little time, just clicked around some on the site and it was having issues all on its own.

Id suggest the use of AcronaiTV for now while the other ones are down or the IPTV list section below em if ya like any of those better.

**Comment by jewbmx** [comment]
Fixed now
