### ISSUE TITLE
Search stopped working

### ISSUE THREAD

**Issue by Ishaichi** [jewbmx/repo#39]
Search results are coming up weird and do not link to anything looks like:

<!CDATA[Name (year)]]>

Is there some way to fix this?

![20191114_195753](https://user-images.githubusercontent.com/57780755/68911327-38b2af80-071a-11ea-8d51-39ebb88402ed.jpg)

**Comment by Ishaichi** [comment]
Addendum: this is on all addons and all lists

**Comment by jewbmx** [comment]
Looks like a personal issue, best advice i got for ya is to ask on reddit about it. All is well on my end
