### ISSUE TITLE
Return feature "filtered" scrappers

### ISSUE THREAD

**Issue by dtizmo** [jewbmx/repo#39]
I have yet to view any sources for rabbitstreams since its inception.  Could you re-enable the ability to choose from "filtered" scrapers? 

Also on the wishlist,  it was nice in the Episode widget  which showed  my shows I regularly watched; illluminated the upcoming episodes (centralized location to easy find shows instead of scrolling through favorites for shows currently in season.

**Comment by jewbmx** [comment]
sounds like your issues are in the addon settings lol
