### ISSUE TITLE
TMDB Helper no search

### ISSUE THREAD

**Issue by devregnfo** [jewbmx/repo#40]
TMDB Helper can't resolve sources with ScrubsV2.
The dialog opens but closes right away with no results...
Is it something you can do? Maybe the search tags are wrong on TMDBH?

Thanks

**Comment by pat-are** [comment]
Hi, it’s seems that a lot of returning tv series has no streams. Is it possible to update Scrubs?

Thanks in advance

**Comment by jayshomebrew** [comment]
@pat-are  
Please try at your work, friends or family's network. Could you be more specific?   See below.

halo s02x04
61 links
![halo 2x4](https://github.com/jewbmx/repo/assets/58111409/0fa7c3f2-dd72-4030-a7dc-e69779ffe164)

true detective s04x06
46 links
![true detective 04x06](https://github.com/jewbmx/repo/assets/58111409/9aca03f7-3c24-43f2-b218-2e2520662a71)

airbender s01x08
33 results
![airbender 01x08](https://github.com/jewbmx/repo/assets/58111409/fc2581b2-3a57-43c0-abef-4f849a61c332)
