### ISSUE TITLE
Sources provide  problems 

### ISSUE THREAD

**Issue by Scott4457** [jewbmx/repo#46]
Hi frist of I got to tell you how much I love your add on it is really great iam just haveing trouble with one source  it is 123moviestv.ne  can you looking in  to it for me but you can looking in to it  when you got time k

**Comment by jewbmx** [comment]
If you can correct your spelling and grammar enough to make it easier to read, i might think about looking into your issue lmao

**Comment by Scott4457** [comment]
Is that better

**Comment by Scott4457** [comment]
Is that better jewbmx

**Comment by Scott4457** [comment]
> If you can correct your spelling and grammar enough to make it easier to read, i might think about looking into your issue

**Comment by Scott4457** [comment]
Hi man was the spelling better

**Comment by Scott4457** [comment]
> If you can correct your spelling and grammar enough to make it easier to read, i might think about looking into your issue lmao

Hi is this better spelling

**Comment by Scott4457** [comment]
> If you can correct your spelling and grammar enough to make it easier to read, i might think about looking into your issue lmao

Is that better spelling
