### ISSUE TITLE
kodi 21 Omega Scrubs v2 Audio Language changed during movie playback in movie collections and new movies probably tv shows

### ISSUE THREAD

**Issue by ghost** [jewbmx/repo#48]
I changed builds from (No Bones About It) to (Nova) build and the Nova build auto installed a different audio language called Libre, when I went back into the build. I would like to reverse that to (American/English) Audio. It changed some movies in movie collections to an unknown language and the new movies don't come in English/American. I went back to (No Bones About It), thinking it would reverse what happened but it didn't. Just changed in Scrubs v2 the Language from (Auto) to (English). I tried factory reset, tried restart, updated, nothing changed. Scrubs v2 won't let me install (a4KSubtitles), in the optional install in tools. I'm getting streams with prmovies, or pro streams, which are not American Audio. Can anybody tell me how to fix this? I don't know much about Kodi or the builds. I would like to reverse this Audio Language back to American/English, can somebody please help me, and help with the (a4ksubtitles), if possible, also help with better streams or sources that work and come in (American/English, Audio?) The only thing I can think of, is if somebody can update the build (No Bones About It), create an auto install of (American/English Audio). I'm Using the Fire Cube 2nd Gen, 2nd Cube. Please tell me what I should do to reverse this or can you guys do this for me? Thank You and have great night.
Chad

**Comment by jayshomebrew** [comment]
FYI, scrubsv2 has nothing to do with the Nova build.  Nevertheless, I'll try and give you some tips:
1. Uninstall kodi app completely from the firestick apps menu, OR
2. use a [kodi program add-on to completely wipe your settings](https://www.firesticktricks.com/reset-kodi-firestick.html), OR
3. use adb/[adblink](http://jocala.com/) to delete your .kodi settings folder.

**Comment by ghost** [comment]
Will this work on my Fire Cube 2nd Gen. I already tried to uninstall kodi completely and reinstalled it and did not work. The Audio comes in a unknown Language called (Libre) which I only have seen on the Nova build. I'm using the (no Bones About It) build by Big Kev in the (Doomzday simple wizard). I hope, I don't have to make a new amazon account. Can I have him make an Auto Installer that installs the American Language as a popup install when u go back into the build. I'll try thanks jay. I did #2 this time and then uninstalled and reinstalled kodi 21 Omega with a build I'm using. Did not work I don't know how to fix this.

**Comment by jewbmx** [comment]
you can solve all your problems by not using builds lmao. time to grow up and find your own favorite skin and addons. it only takes like 5 to 10 min.s to do a fresh install and be all set up by hand.
