### ISSUE TITLE
jewpair

### ISSUE THREAD

**Issue by sdstreams** [jewbmx/repo#6]
Hello, wanted to see if this addon is still being maintained or if there was a matrix version? Looking for a simple rd auth.

thank you

**Comment by jewbmx** [comment]
here ya go, hopefully you can use it without me adding it to the repo properly lol. feelin a little lazy today :)

https://github.com/jewbmx/repo/blob/master/zips/plugin.program.jewpair/plugin.program.jewpair-1.6.zip
its updated to work in kodi 19 and a quick test pulled your rd auth page up on firefox so it seems to be working good enough for your needs.
i didnt bother with all the sources so the hosters are probably dead or out of date.
