### ISSUE TITLE
Kodi 18 settings.xml

### ISSUE THREAD

**Issue by jewbmx** [jewbmx/repo#7]
Found a few issues with Scrubs on Kodi 18 in the settings.

First the trakt option in accounts is glitched out so you have to use the normal menu option in tools to auth otherwise it doesnt seem to show up lol. (Not sure how to fix that.)

Second is another trakt issue for sorting and whatnot which seems to only be glitched out because i moved some of the settings from the first settings tab to the nav tab. (Think that can be fixed by adding them back to the first tab.)

And the Third issue found which ive seen for a while, is that when scrolling around the providers tab it glitches out and goes to the bottom area and fucks the whole settings navigation up. (No idea whats up with that.)

Theres probably more issues but no one else seems to report them and i rarely use 18 lol. Now that 18 is released for droid and the microsoft store i should maybe start to figure this crap out.

**Comment by jewbmx** [comment]
Second part of this issue is fixed now.

**Comment by jewbmx** [comment]
Been playing with the provider settings a little today and think the issue might be caused by a dupe in the list like us scraper and a french one or whatever. Then it dawned on me that maybe the provider tab is just too damn big so i might turn it into 3 tabs of providers and see if that solves the problem.

**Comment by jewbmx** [comment]
Think all of this is now fixed and about to be uploaded.

**Comment by host505** [comment]
Didn't notice this thread earlier, but most of these issues have been discussed (and mostly fixed) over at exodus redux git repo(s)

**Comment by host505** [comment]
Also, trailers crash in leia fix:
https://github.com/host505/plugin.video.theoath/commit/51d6e78f277d23716d2d8fb59fbd46f3f7ec320c#diff-c3f76816c8cdaa1287bfbf69073294a0

**Comment by jewbmx** [comment]
I seen today in my debug that my settings.xml still has some error with the old style but havent looked into it yet till im done in my scraper folder lol.

Also havent had any trailer errors yet but will remember to try that it any get reported.

**Comment by jewbmx** [comment]
Putting it on hold but i think the debug error is a "!eq(-2,false)" issue, and pretty sure i never finished adding the trakt resume features code lmao so i should probably do that too.

**Comment by host505** [comment]
About the trailers problem: try to play a trailer through the information window, through your add-on's menu, not shortcuts etc. on Leia.
