### ISSUE TITLE
Script.module.scrubs failed to install

### ISSUE THREAD

**Issue by amexpak1** [jewbmx/repo#7]
Hi thanks for your hard work. Just was having an issue today trying to install scrubs V2 it's saying it's failing to install the "Script.module.scrubs failed to install dependency".
It's the first time I'm having this issue usually it installs fine just was wondering if you knew if there was a workaround or a fix for it. I'm on Kodi 18.9 fresh install
Thank you

**Comment by jewbmx** [comment]
Imma go ahead and close this issue because i think i just replied to you in a email lol.
As for any lookie-loos, i cleaned the repo today but didnt update much so things are likely broken till i upload my new scrubs version lol. Which should be in the next week or so.
