### ISSUE TITLE
Addon Progress Report

### ISSUE THREAD

**Issue by jewbmx** [jewbmx/repo#9]
This is a simple post to keep upto date with the progress of addons in the repo.
(I will try to keep this updated as needed.)

#Scrubs: updated for 18.
- Scraper updates.
- List updates.

#NiteCrawler: updating for 18.
(The update for 18 resulted in a name change so prev. users probably have to uninstall it completely and maybe even wipe its userdata out. Then install again from the repo lol.)
(Did the same thing to scrubs a while back but did it a little differently, decided not to in this case because imma lazy fucker lmao)
- Search clear needs work.
- List updates.

#On Hold:
- Bearded Bandits(errors unknown)
(lost interest in jen addons, but will try to keep this workin proper.)
- Toontopia(errors unknown)
(lost interest in jen addons, but will try to keep this workin proper.)
- JewCleaner(slowly being redone.)
(Might decide to learn how to make a build for it so i can be super lazy. Which would change the plan for this also lol.)

#To Test:
- JewMC (working/half tested)
(Probably gonna remove the video option and make this all audio so when you click a channel it stays on the selection screen instead of opening everything like a video lol)
(The video channel blows anyways.)
- JewPair(seems to be fine.)
- CoolTVseries(seems to be fine.)

#JewBack'D:
- TinklePad (working/half tested)
( this is just slightly mod'D to work properly as requested.)
- Dbird addon (never tested lol)
(Most likely wont ever touch this again unless asked to.)

**Comment by weekendsource** [comment]
control.py

```
def openSettings(query=None, id=addonInfo('id')):
    try:
        idle()
        execute('Addon.OpenSettings(%s)' % id)
        if query == None: raise Exception()
        c, f = query.split('.')
        if int(getKodiVersion()) >= 18:
            execute('SetFocus(%i)' % (int(c) - 100))
            execute('SetFocus(%i)' % (int(f) - 80))
        else:
            execute('SetFocus(%i)' % (int(c) + 100))
            execute('SetFocus(%i)' % (int(f) + 200))
    except:
        return
```

**Comment by jewbmx** [comment]
Thank you alot for that, tried it a few different times and ways and never got it to work lol.

Added your fix and it works like a charm again :)

**Comment by jewbmx** [comment]
Pretty sure my failed attempts were because i never changed the + to a -

**Comment by weekendsource** [comment]
:) The solution was here:
https://github.com/xbmc/xbmc/issues/14780#issuecomment-435632805

**Comment by weekendsource** [comment]
Working channels.py, a sorely missed feature ;) add it back to your fork if you want:

https://pastebin.com/1xYPQ8BB

**Comment by jewbmx** [comment]
Ive never seen that feature in action so i'll try it for sure. Started using kodi after it stopped working lol

**Comment by host505** [comment]
Thanks @weekendsource for the channels.py fix, I remember reading somewhere that it was unfixable for some reason, so never really bothered.
I'm gonna put it on my fork too if you don't mind :)

**Comment by jewbmx** [comment]
I added it then tossed in a nav setting and made a language line for the label and wound up adding the wrong number in both spots lmao.

**Comment by weekendsource** [comment]
@host505 No problem at all, it's gpl and open source so it belongs to all of us :) There was a slight change of epg api, not a big deal really :) You could also use awk.epgsky.com i.e. https://awk.epgsky.com/hawk/linear/schedule/20190208/4021 and go big with unix time and uk_datetime and full schedule if you want :D but i guess this one is the simplest solution, we are interested in what's now.  

As for channels feature, it's nice to be preserved in all forks since it is here since The Original One :)

**Comment by host505** [comment]
> As for channels feature, it's nice to be preserved in all forks since it is here since The Original One :)

Ah, so I was right when your username reminded me someone from the good ol' tva/xbmchub days :)
Nice to see you around again.

**Comment by weekendsource** [comment]
302, not 404 ;)

**Comment by jewbmx** [comment]
This channels feature supposed to do a normal source search when you click play?

**Comment by bjgood** [comment]
Hey jewbmx,
That's what it's doing for me, too.

**Comment by jewbmx** [comment]
Im guessing from the lack of responses that its working how its supposed to lol. Honestly dont see why its so great if mines working properly, its a glorified userlist that changes lol, i was kinda expecting a dope little movie channel like iptv or something lmao.

**Comment by weekendsource** [comment]
Hehe, it doesn't make sense to someone living in the colonies but it's useful to the inhabitants of UK and Ireland where sky tv rules with an iron fist ;) The main purpose of this feature is, let say, when you are lying on sofa scratching balls and have no idea what to watch - let's see what's on sky right now - click, watch, profit ;)

**Comment by jewbmx** [comment]
Lol thats a good example, still a little sad that it doesnt stream like a iptv option tho.

**Comment by weekendsource** [comment]
docu.py quick fix, you can bring it back if you want: https://pastebin.com/qsq9cTdu

**Comment by jewbmx** [comment]
I can add it back if you use it and want it in, i never spotted any new content with it so i didnt mind it when it broke and i removed it lol
